/**
 * Korean Learning Type - 16 Type Profiles
 * Each profile combines a 4-letter code with campus-life flavored,
 * Korean-learning-specific advice. Not an official MBTI assessment.
 */

const STRONGEST_ADVICE = {
  E: {
    labelKo: "사람들 (PEOPLE)",
    labelEn: "PEOPLE",
    emoji: "💬",
    ko: "사람과 함께할 때 학습 에너지가 크게 올라갑니다. 혼자 외우기보다 말할 상대를 먼저 찾아보세요.",
    en: "You gain energy from studying with people. Find someone to talk to before you sit down to memorize alone.",
  },
  I: {
    labelKo: "몰입 (FOCUS)",
    labelEn: "FOCUS",
    emoji: "🎧",
    ko: "혼자만의 조용한 시간에 학습이 가장 깊어집니다. 방해받지 않는 나만의 공부 루틴을 지켜보세요.",
    en: "You go deepest when you have quiet, uninterrupted time. Protect a study routine that's just for you.",
  },
  S: {
    labelKo: "실전 (PRACTICE)",
    labelEn: "PRACTICE",
    emoji: "🎯",
    ko: "직접 쓰고 반복할 때 실력이 가장 빨리 늡니다. 오늘 배운 표현을 오늘 바로 써보세요.",
    en: "You improve fastest through direct, repeated use. Use today's expression today.",
  },
  N: {
    labelKo: "아이디어 (IDEAS)",
    labelEn: "IDEAS",
    emoji: "🔎",
    ko: "표현 뒤의 맥락과 원리를 이해할 때 오래 기억합니다. '왜 이렇게 말할까'를 스스로 물어보세요.",
    en: "You remember best when you grasp the context and logic behind an expression. Keep asking 'why is it said this way?'",
  },
  T: {
    labelKo: "분석 (LOGIC)",
    labelEn: "LOGIC",
    emoji: "🧩",
    ko: "규칙과 구조를 정리할 때 확실하게 이해됩니다. 문법표나 패턴 노트를 적극 활용하세요.",
    en: "You gain real clarity by organizing rules and structures. Lean into grammar charts and pattern notes.",
  },
  F: {
    labelKo: "소통 (CONNECTION)",
    labelEn: "CONNECTION",
    emoji: "❤️",
    ko: "감정과 관계 속에서 배운 표현이 가장 오래 남습니다. 좋아하는 사람과 나누는 대화를 학습에 적극 연결하세요.",
    en: "Expressions learned through real emotion and relationships stick the longest. Turn conversations with people you like into study material.",
  },
  J: {
    labelKo: "계획 (STRUCTURE)",
    labelEn: "STRUCTURE",
    emoji: "📅",
    ko: "목표와 일정이 있을 때 꾸준히 나아갑니다. 작은 목표라도 눈에 보이게 적어두세요.",
    en: "You make steady progress when there's a clear goal and timeline. Write even small goals down where you can see them.",
  },
  P: {
    labelKo: "자유 (FLEXIBILITY)",
    labelEn: "FLEXIBILITY",
    emoji: "🌊",
    ko: "정해진 틀보다 자유로운 탐색 속에서 더 잘 배웁니다. 흥미가 이끄는 대로 따라가되, 하루 한 가지만 기록해보세요.",
    en: "You learn better through free exploration than rigid structure. Follow your curiosity, but jot down just one thing each day.",
  },
};

function studyBuddyText(code, ko, en) {
  return { code, ko, en };
}

const PROFILES = {
  ENFP: {
    code: "ENFP",
    emoji: "🚀",
    titleKo: "자유로운 한국어 탐험가",
    titleEn: "The Free Korean Explorer",
    taglineKo: "사람과 배우고, 맥락으로 이해하고, 마음으로 소통하고, 자유롭게 탐색하는 학습자",
    taglineEn: "You learn with people, through context, from the heart, and always exploring freely.",
    descriptionKo: "새로운 표현, 새로운 사람, 새로운 상황을 만나면 눈이 반짝여요. 규칙보다는 '이 말을 실제로 어떻게 쓸까'가 더 궁금한 타입이에요. 계획표보다 오늘의 대화가 진짜 교과서예요.",
    descriptionEn: "Your eyes light up at new expressions, new people, new situations. You're more curious about how a phrase is actually used than the rule behind it. Today's conversation is your real textbook.",
    strengths: [
      { ko: "낯선 사람에게도 먼저 한국어로 말을 걸 수 있어요.", en: "You can start a Korean conversation with a stranger without hesitation." },
      { ko: "새로운 표현을 빠르게 흡수하고 응용해요.", en: "You quickly absorb and apply new expressions." },
      { ko: "학습을 놀이처럼 즐겨서 지치지 않아요.", en: "You treat learning like play, so you rarely burn out." },
    ],
    cautions: [
      { ko: "흥미가 식으면 마무리를 잘 못 지어요.", en: "You can lose steam finishing things once the novelty fades." },
      { ko: "문법 정리처럼 반복적인 작업은 쉽게 지루해해요.", en: "Repetitive tasks like grammar drills bore you quickly." },
    ],
    bestMethods: [
      { ko: "언어교환 파트너와 매일 짧게 대화하기", en: "Daily short conversations with a language exchange partner" },
      { ko: "좋아하는 K-콘텐츠로 표현 수집하기", en: "Collecting expressions from K-content you actually enjoy" },
      { ko: "배운 표현을 SNS에 바로 써보기", en: "Using new expressions on social media right away" },
    ],
    skills: {
      listening: { ko: "예능이나 브이로그처럼 사람 냄새 나는 콘텐츠로 들어보세요. 자막 없이 감으로 먼저 즐기는 게 좋아요.", en: "Try variety shows or vlogs full of real personality. Enjoy them without subtitles first, using your instincts." },
      speaking: { ko: "완벽한 문장보다 일단 던져보는 게 중요해요. 실수해도 대화가 이어진다는 걸 몸으로 익히세요.", en: "Don't wait for a perfect sentence — just say something. Learn by feel that mistakes don't stop a conversation." },
      reading: { ko: "긴 글보다 대화형 텍스트, 채팅, 짧은 에세이가 잘 맞아요.", en: "Dialogue-style texts, chats, and short essays suit you better than long articles." },
      writing: { ko: "일기보다 메시지나 댓글처럼 실제로 누군가에게 보내는 글이 동기부여가 돼요.", en: "Writing to an actual person — a message or comment — motivates you more than a private journal." },
    },
    difficultMethod: {
      titleKo: "이렇게 공부하면 쉽게 지칠 수 있어요",
      titleEn: "This approach can drain you fast",
      ko: "단어장을 처음부터 끝까지 순서대로 두 시간 동안 계속 외우기",
      en: "Memorizing a vocabulary list from start to finish for two straight hours",
    },
    alternativeMethod: {
      ko: "15분 단위로 나누고, 외운 단어를 바로 문장이나 대화에 써보세요.",
      en: "Break it into 15-minute chunks and immediately use each word in a sentence or conversation.",
    },
    contentRecommendations: [
      { ko: "한국 예능·브이로그 유튜브 채널", en: "Korean variety show / vlog YouTube channels" },
      { ko: "언어교환 앱의 짧은 음성 메시지 기능", en: "Voice message features on language exchange apps" },
      { ko: "밈과 유행어 정리 콘텐츠", en: "Content curating current memes and slang" },
    ],
    campusMission: {
      ko: "오늘 한국 친구에게 “요즘 뭐가 제일 재미있어요?” 라고 먼저 물어보세요.",
      en: "Today, be the first to ask a Korean friend, \"What's the most fun thing lately?\"",
    },
    studyBuddy: studyBuddyText("ISTJ", "한 명은 새로운 활동을 시작하고, 한 명은 계획대로 끝까지 갑니다. 완벽한 밸런스!", "One starts new things, the other finishes what's planned. A perfect balance!"),
    funCombo: studyBuddyText("ENTP", "아이디어는 100개, 오늘 끝낸 공부는... 2개? 😆 그래도 제일 신나는 스터디 조합.", "100 ideas, but only 2 finished today? 😆 Still the most fun study combo around."),
    meme: {
      ko: "선생님: “32페이지 펴세요.”\nENFP: “근데 이 표현 진짜 한국 사람들이 써요?”",
      en: "Teacher: \"Turn to page 32.\"\nENFP: \"But do Koreans actually say this in real life?\"",
    },
    challenge7Days: [
      { day: 1, ko: "오늘 만난 사람에게 배운 표현 1개 써보기", en: "Use one new expression on someone you meet today" },
      { day: 2, ko: "좋아하는 K-콘텐츠에서 표현 3개 수집하기", en: "Collect 3 expressions from K-content you enjoy" },
      { day: 3, ko: "모은 표현을 실제 대화나 채팅에서 사용하기", en: "Use your collected expressions in a real chat" },
      { day: 4, ko: "어제 쓴 표현 중 가장 재밌었던 것 복습하기", en: "Review the most fun expression from yesterday" },
      { day: 5, ko: "낯선 장소(카페, 편의점 등)에서 한국어로 먼저 말 걸기", en: "Speak first in Korean at a new place (cafe, convenience store)" },
      { day: 6, ko: "이번 주 배운 표현으로 짧은 SNS 게시물 쓰기", en: "Write a short social post using this week's expressions" },
      { day: 7, ko: "일주일 중 가장 재밌었던 한국어 순간 친구에게 이야기하기", en: "Tell a friend about your favorite Korean moment of the week" },
    ],
  },

  ENFJ: {
    code: "ENFJ",
    emoji: "🤝",
    titleKo: "캠퍼스 소통 리더",
    titleEn: "The Campus Connector",
    taglineKo: "사람과 배우고, 맥락으로 이해하고, 마음으로 소통하고, 계획을 세워 이끄는 학습자",
    taglineEn: "You learn with people, through context, from the heart, and with a plan to guide others.",
    descriptionKo: "혼자 배우는 것보다 함께 배울 때 더 힘이 나요. 스터디 그룹에서 자연스럽게 분위기를 이끌고, 친구가 어려워하면 먼저 도와주고 싶어져요.",
    descriptionEn: "You get more energy learning with others than alone. You naturally guide the mood in study groups, and want to help the moment a friend struggles.",
    strengths: [
      { ko: "스터디 그룹을 자연스럽게 이끌어요.", en: "You naturally lead study groups." },
      { ko: "다른 사람의 학습까지 챙기며 함께 성장해요.", en: "You grow together by caring about others' progress too." },
      { ko: "목표를 세우면 꾸준히 실천해요.", en: "Once you set a goal, you follow through consistently." },
    ],
    cautions: [
      { ko: "남을 챙기다가 정작 내 공부는 미룰 수 있어요.", en: "You may put off your own study while helping others." },
      { ko: "관계가 불편해지면 학습 동기도 함께 떨어져요.", en: "Your motivation can drop when a relationship feels off." },
    ],
    bestMethods: [
      { ko: "스터디 그룹 만들어서 함께 목표 세우기", en: "Forming a study group and setting shared goals" },
      { ko: "배운 내용을 다른 사람에게 설명해보기", en: "Explaining what you learned to someone else" },
      { ko: "정기적인 언어교환 모임 참여하기", en: "Joining a regular language exchange meetup" },
    ],
    skills: {
      listening: { ko: "토크쇼나 인터뷰처럼 사람 간의 대화가 중심인 콘텐츠가 잘 맞아요.", en: "Talk shows and interviews centered on real conversation suit you well." },
      speaking: { ko: "그룹 스터디에서 돌아가며 말하는 연습이 효과적이에요.", en: "Taking turns speaking in a group study session works great for you." },
      reading: { ko: "함께 읽고 토론할 수 있는 짧은 이야기나 칼럼이 좋아요.", en: "Short stories or columns you can read and discuss with others suit you." },
      writing: { ko: "친구에게 보내는 편지나 그룹 채팅 요약 쓰기로 연습하세요.", en: "Practice by writing letters to friends or summarizing group chats." },
    },
    difficultMethod: {
      titleKo: "이렇게 공부하면 쉽게 지칠 수 있어요",
      titleEn: "This approach can drain you fast",
      ko: "아무와도 나누지 않고 혼자 몇 시간씩 문제집 풀기",
      en: "Solving workbooks alone for hours without sharing with anyone",
    },
    alternativeMethod: {
      ko: "친구와 함께 문제를 풀고 서로 설명해주는 방식으로 바꿔보세요.",
      en: "Try solving problems with a friend and explaining answers to each other.",
    },
    contentRecommendations: [
      { ko: "한국 토크쇼, 인터뷰 콘텐츠", en: "Korean talk shows and interview content" },
      { ko: "스터디 메이트 매칭 앱", en: "Study buddy matching apps" },
      { ko: "함께 읽는 온라인 북클럽", en: "Online book clubs you can join with others" },
    ],
    campusMission: {
      ko: "오늘 스터디 그룹을 하나 만들고, 이번 주 목표를 함께 정해보세요.",
      en: "Today, start a study group and set this week's goal together.",
    },
    studyBuddy: studyBuddyText("ISTP", "한 명은 사람을 모으고, 한 명은 문제를 해결해요. 든든한 조합이에요.", "One brings people together, the other solves the problems. A rock-solid team."),
    funCombo: studyBuddyText("ENTJ", "둘 다 리더 기질! 스터디 그룹 하나에 회장이 두 명이 될 수도 있어요 😆", "Both natural leaders! One study group might end up with two presidents 😆"),
    meme: {
      ko: "ENFJ: “얘들아 우리 스터디 그룹 만들자!”\n(다음 날) ENFJ: “다들 숙제 했지? 안 했으면 지금 같이 하자!”",
      en: "ENFJ: \"Guys, let's start a study group!\"\n(Next day) ENFJ: \"Did everyone do the homework? If not, let's do it together now!\"",
    },
    challenge7Days: [
      { day: 1, ko: "함께 공부할 친구 한 명에게 먼저 연락하기", en: "Reach out to one friend to study together" },
      { day: 2, ko: "좋아하는 K-콘텐츠 속 대화 표현 배우기", en: "Learn conversational expressions from K-content you enjoy" },
      { day: 3, ko: "배운 표현을 스터디 친구에게 직접 설명해주기", en: "Explain a new expression to your study friend" },
      { day: 4, ko: "그룹 채팅방에서 한국어로 오늘 하루 요약하기", en: "Summarize your day in Korean in a group chat" },
      { day: 5, ko: "친구의 한국어 실수를 다정하게 고쳐주기", en: "Gently correct a friend's Korean mistake" },
      { day: 6, ko: "그룹 언어교환 모임 한 번 참여해보기", en: "Attend one group language exchange meetup" },
      { day: 7, ko: "이번 주 함께한 스터디 친구에게 고마움 표현하기", en: "Thank your study friend for the week in Korean" },
    ],
  },

  ENTP: {
    code: "ENTP",
    emoji: "💡",
    titleKo: "한국어 아이디어 해커",
    titleEn: "The Korean Idea Hacker",
    taglineKo: "사람과 배우고, 맥락으로 이해하고, 논리로 분석하고, 자유롭게 탐색하는 학습자",
    taglineEn: "You learn with people, through context, with logic, and always exploring freely.",
    descriptionKo: "“이 표현, 다르게 쓰면 어떻게 될까?” 하고 계속 실험해보는 타입이에요. 규칙을 배우면 바로 비틀어보고 싶어지고, 토론할 때 한국어 실력이 가장 빨리 늘어요.",
    descriptionEn: "You're the type who keeps asking \"what if I say it this way instead?\" The moment you learn a rule, you want to bend it, and your Korean improves fastest in debate.",
    strengths: [
      { ko: "표현을 새로운 방식으로 응용하는 데 능해요.", en: "You're great at applying expressions in new ways." },
      { ko: "논쟁이나 토론 상황에서 순발력 있게 말해요.", en: "You think fast on your feet in debates and discussions." },
      { ko: "지루하지 않게 스스로 학습법을 계속 바꿔요.", en: "You keep reinventing your own study method so it never gets boring." },
    ],
    cautions: [
      { ko: "기초를 다지는 반복 학습을 건너뛰고 싶어해요.", en: "You're tempted to skip the repetitive drills that build basics." },
      { ko: "새로운 아이디어에 꽂히면 원래 계획을 잊어요.", en: "A new idea can make you forget the original plan." },
    ],
    bestMethods: [
      { ko: "찬반 토론 스터디로 말하기 연습하기", en: "Practicing speaking through debate-style study sessions" },
      { ko: "배운 표현을 일부러 다른 상황에 억지로 써보기", en: "Deliberately using a new expression in an unrelated situation" },
      { ko: "궁금한 문법을 스스로 파고들어 규칙 찾아보기", en: "Digging into a grammar point yourself to find the underlying rule" },
    ],
    skills: {
      listening: { ko: "시사·토론 프로그램처럼 논리가 살아있는 콘텐츠가 잘 맞아요.", en: "Discussion or current-affairs programs full of logic suit you well." },
      speaking: { ko: "즉흥 토론이나 ‘왜?’로 시작하는 질문 놀이로 연습하세요.", en: "Practice with impromptu debates or a game of asking 'why?'" },
      reading: { ko: "칼럼, 의견 글처럼 주장이 담긴 글을 읽고 반박해보세요.", en: "Read opinion columns and practice arguing back." },
      writing: { ko: "정해진 형식보다 자유 형식의 에세이나 블로그 글이 잘 맞아요.", en: "Free-form essays or blog posts suit you better than fixed formats." },
    },
    difficultMethod: {
      titleKo: "이렇게 공부하면 쉽게 지칠 수 있어요",
      titleEn: "This approach can drain you fast",
      ko: "똑같은 패턴의 문제를 정해진 순서대로 반복해서 풀기",
      en: "Repeating the same pattern of problems in a fixed order",
    },
    alternativeMethod: {
      ko: "같은 문법으로 스스로 새로운 예문을 만들어보는 방식으로 바꿔보세요.",
      en: "Try making your own new example sentences with the same grammar instead.",
    },
    contentRecommendations: [
      { ko: "시사 토론 유튜브 채널", en: "Current-affairs debate YouTube channels" },
      { ko: "한국어 밈·언어유희 콘텐츠", en: "Korean memes and wordplay content" },
      { ko: "온라인 토론 커뮤니티", en: "Online debate communities" },
    ],
    campusMission: {
      ko: "오늘 배운 표현을 원래 뜻과 다른 상황에서 한 번 써보세요.",
      en: "Today, use a new expression in a situation it wasn't originally meant for.",
    },
    studyBuddy: studyBuddyText("ISFJ", "한 명은 새 아이디어를 던지고, 한 명은 꼼꼼히 마무리해요. 완성도 최고 조합.", "One throws out new ideas, the other polishes them carefully. Top-tier completion rate."),
    funCombo: studyBuddyText("ENFP", "아이디어는 100개, 오늘 끝낸 공부는... 2개? 😆", "100 ideas, but only 2 finished today? 😆"),
    meme: {
      ko: "ENTP: “이 문법, 이렇게 쓰면 안 돼요?”\n선생님: “...문법책에 없는데요.”\nENTP: “그럼 제가 만들죠 뭐.”",
      en: "ENTP: \"Can I use this grammar this way instead?\"\nTeacher: \"...that's not in the textbook.\"\nENTP: \"Guess I'll invent it, then.\"",
    },
    challenge7Days: [
      { day: 1, ko: "오늘 배운 표현을 엉뚱한 상황에 써보기", en: "Use today's expression in an unexpected situation" },
      { day: 2, ko: "궁금했던 문법 하나 스스로 검색해서 원리 찾기", en: "Look up a grammar point you're curious about and find the logic" },
      { day: 3, ko: "친구와 짧은 찬반 토론 해보기", en: "Have a short debate with a friend" },
      { day: 4, ko: "어제 만든 예문 다시 써보고 더 재밌게 바꾸기", en: "Revisit yesterday's example sentence and make it more fun" },
      { day: 5, ko: "새로운 표현으로 짧은 유머 문장 만들어보기", en: "Make a short joke using a new expression" },
      { day: 6, ko: "한 주간 만든 예문들 모아 정리하기", en: "Collect all the example sentences you made this week" },
      { day: 7, ko: "가장 마음에 든 예문을 친구에게 자랑하기", en: "Show off your favorite example sentence to a friend" },
    ],
  },

  ENTJ: {
    code: "ENTJ",
    emoji: "🎯",
    titleKo: "한국어 레벨업 전략가",
    titleEn: "The Korean Level-Up Strategist",
    taglineKo: "사람과 배우고, 맥락으로 이해하고, 논리로 분석하고, 계획을 세워 이끄는 학습자",
    taglineEn: "You learn with people, through context, with logic, and with a clear strategic plan.",
    descriptionKo: "목표가 명확할 때 가장 빨리 늘어요. “한 달 안에 TOPIK 3급”처럼 구체적인 목표를 세우고, 그걸 향해 효율적으로 밀어붙이는 걸 좋아해요.",
    descriptionEn: "You improve fastest with a clear goal. You love setting concrete targets — like \"TOPIK level 3 in a month\" — and pushing efficiently toward them.",
    strengths: [
      { ko: "목표와 로드맵을 명확하게 세워요.", en: "You set clear goals and roadmaps." },
      { ko: "비효율적인 공부법을 빠르게 바꿔요.", en: "You quickly cut out inefficient study methods." },
      { ko: "스터디 그룹의 방향을 능숙하게 이끌어요.", en: "You skillfully steer the direction of a study group." },
    ],
    cautions: [
      { ko: "결과에 집중하다 학습 자체의 재미를 놓칠 수 있어요.", en: "Focusing on results can make you miss the fun of learning itself." },
      { ko: "계획대로 안 되면 스트레스를 크게 받아요.", en: "You get very stressed when things don't go as planned." },
    ],
    bestMethods: [
      { ko: "TOPIK 등 명확한 목표 세우고 역산 계획 짜기", en: "Setting a clear goal like TOPIK and working backward" },
      { ko: "주간 성취 체크리스트로 진도 관리하기", en: "Tracking progress with a weekly achievement checklist" },
      { ko: "스터디 그룹의 커리큘럼을 직접 설계하기", en: "Designing the curriculum for your own study group" },
    ],
    skills: {
      listening: { ko: "뉴스나 시사 브리핑처럼 정보 밀도가 높은 콘텐츠가 잘 맞아요.", en: "Dense, information-rich content like news briefings suits you well." },
      speaking: { ko: "발표나 프레젠테이션 형식으로 말하기 연습을 해보세요.", en: "Practice speaking in a presentation format." },
      reading: { ko: "보고서, 기사처럼 구조가 명확한 글을 읽으세요.", en: "Read clearly structured texts like reports and articles." },
      writing: { ko: "목표와 근거가 뚜렷한 논리적인 글쓰기가 잘 맞아요.", en: "Logical writing with a clear thesis and evidence suits you well." },
    },
    difficultMethod: {
      titleKo: "이렇게 공부하면 쉽게 지칠 수 있어요",
      titleEn: "This approach can drain you fast",
      ko: "목표나 기준 없이 그냥 ‘재미로’ 이것저것 공부하기",
      en: "Studying random things \"just for fun\" with no goal or benchmark",
    },
    alternativeMethod: {
      ko: "아주 작은 것이라도 이번 주의 구체적인 목표를 하나 정해보세요.",
      en: "Even something small — set one concrete goal for this week.",
    },
    contentRecommendations: [
      { ko: "한국어 뉴스 브리핑", en: "Korean news briefings" },
      { ko: "TOPIK 급수별 목표 콘텐츠", en: "TOPIK level-based goal content" },
      { ko: "자기계발·생산성 유튜브 채널", en: "Self-development / productivity YouTube channels" },
    ],
    campusMission: {
      ko: "오늘 이번 주 한국어 목표를 딱 한 문장으로 적어보세요.",
      en: "Today, write down this week's Korean goal in exactly one sentence.",
    },
    studyBuddy: studyBuddyText("ISFP", "한 명은 방향을 잡고, 한 명은 감성을 더해요. 서로에게 없는 걸 채워줘요.", "One sets the direction, the other adds heart. You fill in what the other lacks."),
    funCombo: studyBuddyText("ENFJ", "둘 다 리더 기질! 스터디 그룹 하나에 회장이 두 명이 될 수도 있어요 😆", "Both natural leaders! One study group might end up with two presidents 😆"),
    meme: {
      ko: "시험 D-14\n다른 학생: 😱\nENTJ: 이미 D-30부터 계획표 3단계로 완성함 ✅",
      en: "Exam in 14 days\nOther student: 😱\nENTJ: Already finished a 3-phase plan since day 30 ✅",
    },
    challenge7Days: [
      { day: 1, ko: "이번 주 한국어 목표 한 문장으로 적기", en: "Write this week's Korean goal in one sentence" },
      { day: 2, ko: "목표를 위한 하루 학습량 정하기", en: "Set a daily study amount toward that goal" },
      { day: 3, ko: "오늘 학습량 달성 여부 체크하기", en: "Check whether you hit today's study amount" },
      { day: 4, ko: "비효율적이었던 방법 하나 바꿔보기", en: "Replace one method that wasn't efficient" },
      { day: 5, ko: "배운 내용으로 짧은 발표 연습하기", en: "Practice a short presentation using what you learned" },
      { day: 6, ko: "이번 주 진도를 체크리스트로 점검하기", en: "Review this week's progress with a checklist" },
      { day: 7, ko: "다음 주 목표 미리 세우기", en: "Set next week's goal in advance" },
    ],
  },

  ESFP: {
    code: "ESFP",
    emoji: "🎉",
    titleKo: "캠퍼스 인싸 스피커",
    titleEn: "The Campus Social Speaker",
    taglineKo: "사람과 배우고, 경험 중심으로 이해하고, 마음으로 소통하고, 자유롭게 탐색하는 학습자",
    taglineEn: "You learn with people, through real experience, from the heart, and always exploring freely.",
    descriptionKo: "말하는 것 자체가 즐거운 타입이에요. 문법보다 “지금 당장 써먹을 수 있는 말”에 관심이 많고, 사람들과 왁자지껄하게 어울리며 한국어가 자연스럽게 늘어요.",
    descriptionEn: "For you, speaking itself is fun. You care more about \"what I can say right now\" than grammar rules, and your Korean grows naturally through lively hangouts with people.",
    strengths: [
      { ko: "말하기에 두려움이 없고 실전 감각이 뛰어나요.", en: "You're fearless when speaking and have great real-world instincts." },
      { ko: "분위기를 살리며 대화를 즐겁게 이끌어요.", en: "You liven up the mood and keep conversations fun." },
      { ko: "유행 표현이나 신조어를 빠르게 습득해요.", en: "You quickly pick up trending expressions and slang." },
    ],
    cautions: [
      { ko: "정확한 문법보다 느낌으로 넘어가는 습관이 있어요.", en: "You tend to rely on feel rather than precise grammar." },
      { ko: "혼자 하는 반복 학습을 지루해해요.", en: "Solo repetitive study bores you." },
    ],
    bestMethods: [
      { ko: "실제 사람들과 어울리는 모임에서 바로 말해보기", en: "Speaking up right away at real social gatherings" },
      { ko: "유행어와 밈으로 표현 익히기", en: "Learning expressions through slang and memes" },
      { ko: "롤플레이로 실전 상황 연습하기", en: "Practicing real-life situations through roleplay" },
    ],
    skills: {
      listening: { ko: "예능, 챌린지 영상처럼 에너지 넘치는 콘텐츠가 잘 맞아요.", en: "High-energy content like variety shows and challenge videos suits you well." },
      speaking: { ko: "실제 모임이나 파티에서 바로 실전으로 연습하세요.", en: "Practice live at real meetups or parties." },
      reading: { ko: "짧고 재밌는 SNS 캡션이나 채팅으로 시작하세요.", en: "Start with short, fun social captions or chat messages." },
      writing: { ko: "감정을 담은 짧은 메시지나 캡션 쓰기가 잘 맞아요.", en: "Short, emotion-filled messages or captions suit you well." },
    },
    difficultMethod: {
      titleKo: "이렇게 공부하면 쉽게 지칠 수 있어요",
      titleEn: "This approach can drain you fast",
      ko: "혼자 조용히 앉아서 문법책만 몇 시간씩 정독하기",
      en: "Sitting quietly alone reading only a grammar textbook for hours",
    },
    alternativeMethod: {
      ko: "배운 문법을 바로 친구와의 대화에 넣어 실전으로 확인해보세요.",
      en: "Immediately test a new grammar point in a real conversation with a friend.",
    },
    contentRecommendations: [
      { ko: "한국 예능·챌린지 영상", en: "Korean variety shows and challenge videos" },
      { ko: "SNS 밈·유행어 계정", en: "Meme and slang social accounts" },
      { ko: "댄스·챌린지와 함께하는 표현 학습 콘텐츠", en: "Expression-learning content paired with dance/challenges" },
    ],
    campusMission: {
      ko: "오늘 처음 만나는 사람에게 유행어 하나를 배워서 바로 써보세요.",
      en: "Today, learn a piece of slang from someone new and use it right away.",
    },
    studyBuddy: studyBuddyText("INTJ", "한 명은 분위기를 띄우고, 한 명은 깊이를 더해요. 뜻밖에 잘 맞는 조합.", "One brings the energy, the other brings the depth. A surprisingly great match."),
    funCombo: studyBuddyText("ESTP", "둘 다 일단 저지르고 보는 스타일! 계획은 없지만 재미는 확실해요.", "Both act first, plan later! No plan, but guaranteed fun."),
    meme: {
      ko: "ESFP: 문법은 몰라도 분위기로 다 알아들어요.\n(사실 절반은 못 알아들음) 🎉",
      en: "ESFP: I don't know the grammar, but I get it from the vibe.\n(Actually only understood half) 🎉",
    },
    challenge7Days: [
      { day: 1, ko: "오늘 새로 배운 유행어 하나 실제로 써보기", en: "Use a newly learned slang word in real life" },
      { day: 2, ko: "예능 속 표현 하나 따라해보기", en: "Mimic one expression from a variety show" },
      { day: 3, ko: "친구들과 롤플레이로 실전 상황 연습하기", en: "Practice a real-life scenario via roleplay with friends" },
      { day: 4, ko: "오늘 있었던 재밌는 일 한국어로 이야기하기", en: "Tell a friend about something fun today, in Korean" },
      { day: 5, ko: "새로운 모임이나 행사에 참여해서 말 걸어보기", en: "Join a new gathering or event and strike up conversation" },
      { day: 6, ko: "이번 주 배운 표현으로 짧은 영상 캡션 쓰기", en: "Write a short video caption using this week's expressions" },
      { day: 7, ko: "가장 재밌었던 한국어 순간 친구에게 자랑하기", en: "Brag to a friend about your favorite Korean moment" },
    ],
  },

  ESFJ: {
    code: "ESFJ",
    emoji: "💕",
    titleKo: "친화력 만렙 학습러",
    titleEn: "The Ultra-Sociable Learner",
    taglineKo: "사람과 배우고, 경험 중심으로 이해하고, 마음으로 소통하고, 계획을 세워 나아가는 학습자",
    taglineEn: "You learn with people, through real experience, from the heart, and with steady structure.",
    descriptionKo: "함께하는 사람들과 좋은 관계를 유지하면서 꾸준히 공부하는 타입이에요. 정해진 스터디 루틴을 잘 지키고, 친구들을 세심하게 챙기며 함께 성장해요.",
    descriptionEn: "You study steadily while keeping good relationships with the people around you. You stick to a study routine and grow together by caring for your friends closely.",
    strengths: [
      { ko: "약속한 스터디 일정을 성실하게 지켜요.", en: "You faithfully keep study appointments and schedules." },
      { ko: "함께하는 사람을 세심하게 챙겨요.", en: "You look after your study companions thoughtfully." },
      { ko: "실생활 예문을 통해 안정적으로 배워요.", en: "You learn steadily through practical, everyday examples." },
    ],
    cautions: [
      { ko: "관계 유지에 신경 쓰다 정작 공부 시간이 줄 수 있어요.", en: "Focusing on relationships can eat into your actual study time." },
      { ko: "낯선 방식보다 익숙한 방법만 고집할 수 있어요.", en: "You may stick only to familiar methods, avoiding new ones." },
    ],
    bestMethods: [
      { ko: "정기 스터디 모임으로 루틴 만들기", en: "Building a routine through regular study meetups" },
      { ko: "실생활 대화 예문으로 표현 익히기", en: "Learning expressions through everyday conversation examples" },
      { ko: "친구와 서로 숙제 체크해주기", en: "Checking each other's homework with a friend" },
    ],
    skills: {
      listening: { ko: "일상 브이로그나 가족·친구 간 대화 콘텐츠가 잘 맞아요.", en: "Everyday vlogs or content featuring family/friend conversations suit you well." },
      speaking: { ko: "친한 친구와의 편안한 대화에서 자연스럽게 늘어요.", en: "You improve naturally through relaxed chats with close friends." },
      reading: { ko: "생활 정보, 요리, 일상 팁을 다룬 글이 잘 맞아요.", en: "Practical everyday texts — recipes, life tips — suit you well." },
      writing: { ko: "친구에게 안부를 묻는 메시지로 쓰기 연습을 시작하세요.", en: "Start writing practice with check-in messages to friends." },
    },
    difficultMethod: {
      titleKo: "이렇게 공부하면 쉽게 지칠 수 있어요",
      titleEn: "This approach can drain you fast",
      ko: "누구와도 상관없이 혼자 새로운 학습 앱을 계속 바꿔가며 시도하기",
      en: "Constantly switching between new solo study apps with no one to share it with",
    },
    alternativeMethod: {
      ko: "믿을 수 있는 친구 한 명과 같은 방법으로 함께 꾸준히 해보세요.",
      en: "Stick with one trusted friend and the same method, consistently.",
    },
    contentRecommendations: [
      { ko: "일상 브이로그 콘텐츠", en: "Everyday life vlog content" },
      { ko: "생활 밀착형 한국어 팟캐스트", en: "Practical, everyday-life Korean podcasts" },
      { ko: "친구와 함께 하는 스터디 앱", en: "Study apps designed for studying with friends" },
    ],
    campusMission: {
      ko: "오늘 친구 한 명에게 안부를 묻는 한국어 메시지를 먼저 보내보세요.",
      en: "Today, send a friend a Korean message checking in on them first.",
    },
    studyBuddy: studyBuddyText("INTP", "한 명은 관계를 챙기고, 한 명은 원리를 파고들어요. 서로의 빈틈을 채워줘요.", "One tends the relationship, the other digs into the logic. You fill each other's gaps."),
    funCombo: studyBuddyText("ESTJ", "둘 다 계획형! 스터디 시간표가 분 단위로 완벽하게 짜여요.", "Both planners! Your study schedule ends up planned down to the minute."),
    meme: {
      ko: "ESFJ: “오늘 숙제 다 했어? 안 했으면 내가 도와줄게!”\n(정작 본인 숙제는 아직...) 😅",
      en: "ESFJ: \"Did you finish today's homework? I'll help if not!\"\n(Hasn't finished their own yet...) 😅",
    },
    challenge7Days: [
      { day: 1, ko: "친구에게 안부 메시지 한국어로 보내기", en: "Send a friend a check-in message in Korean" },
      { day: 2, ko: "오늘 배운 생활 표현 하나 실제로 써보기", en: "Use a new everyday expression in real life" },
      { day: 3, ko: "스터디 친구와 숙제 서로 체크해주기", en: "Check homework with a study friend" },
      { day: 4, ko: "가족이나 친구 이야기하는 짧은 글 써보기", en: "Write a short piece about family or friends" },
      { day: 5, ko: "정기 스터디 모임 한 번 참여하기", en: "Attend a regular study meetup" },
      { day: 6, ko: "이번 주 도와준 친구에게 고마움 표현하기", en: "Thank a friend who helped you this week" },
      { day: 7, ko: "다음 주 스터디 일정 함께 정하기", en: "Plan next week's study schedule together" },
    ],
  },

  ESTP: {
    code: "ESTP",
    emoji: "⚡",
    titleKo: "실전 한국어 플레이어",
    titleEn: "The Real-World Korean Player",
    taglineKo: "사람과 배우고, 경험 중심으로 이해하고, 논리로 분석하고, 자유롭게 탐색하는 학습자",
    taglineEn: "You learn with people, through real experience, with logic, and always exploring freely.",
    descriptionKo: "이론보다 실전이에요. 일단 상황에 부딪혀보고, 거기서 배운 걸 바로 다음에 써먹는 타입이에요. 빠른 판단력으로 실제 대화 상황에 강해요.",
    descriptionEn: "You're all about real-world practice over theory. You jump into a situation, then immediately apply what you learned to the next one. Your quick judgment makes you strong in live conversation.",
    strengths: [
      { ko: "실제 상황에서 순발력 있게 대응해요.", en: "You react quickly and confidently in real situations." },
      { ko: "실수를 두려워하지 않고 바로 시도해요.", en: "You're not afraid of mistakes and try things right away." },
      { ko: "몸으로 부딪히며 배운 건 오래 기억해요.", en: "What you learn hands-on, you remember for a long time." },
    ],
    cautions: [
      { ko: "이론이나 문법 설명을 지루해할 수 있어요.", en: "You may find theory or grammar explanations tedious." },
      { ko: "장기 계획 없이 그때그때 하다 흐름이 끊길 수 있어요.", en: "Without a long-term plan, your momentum can stall." },
    ],
    bestMethods: [
      { ko: "실제 상황(주문, 길찾기 등)에서 바로 써보기", en: "Trying it live in real situations (ordering, asking directions)" },
      { ko: "게임이나 챌린지 형식으로 학습하기", en: "Studying through games or challenge formats" },
      { ko: "짧고 굵게, 매일 조금씩 실전 연습하기", en: "Short, intense daily bursts of real-world practice" },
    ],
    skills: {
      listening: { ko: "스포츠 중계나 리얼리티 예능처럼 생동감 있는 콘텐츠가 잘 맞아요.", en: "Lively content like sports commentary or reality shows suits you well." },
      speaking: { ko: "실제 매장, 거리에서 바로 부딪혀보며 연습하세요.", en: "Practice by jumping straight into real stores and streets." },
      reading: { ko: "메뉴판, 표지판처럼 실생활에서 마주치는 텍스트로 시작하세요.", en: "Start with real-life text you actually encounter — menus, signs." },
      writing: { ko: "짧고 실용적인 메모나 후기 쓰기가 잘 맞아요.", en: "Short, practical notes or reviews suit you well." },
    },
    difficultMethod: {
      titleKo: "이렇게 공부하면 쉽게 지칠 수 있어요",
      titleEn: "This approach can drain you fast",
      ko: "문법 이론을 순서대로 차분히 읽고 정리하기",
      en: "Calmly reading and organizing grammar theory in order",
    },
    alternativeMethod: {
      ko: "이론은 최소한만 보고, 바로 실전 상황에서 시행착오로 익혀보세요.",
      en: "Skim the theory to the bare minimum, then learn through trial and error in real situations.",
    },
    contentRecommendations: [
      { ko: "리얼리티 예능·서바이벌 프로그램", en: "Reality shows and survival programs" },
      { ko: "실전 회화 챌린지 콘텐츠", en: "Real-conversation challenge content" },
      { ko: "여행 브이로그 속 실전 표현", en: "Practical expressions from travel vlogs" },
    ],
    campusMission: {
      ko: "오늘 학교 밖 가게에서 한국어로 직접 주문해보세요.",
      en: "Today, order something in Korean at a shop off campus.",
    },
    studyBuddy: studyBuddyText("INFJ", "한 명은 부딪히며 배우고, 한 명은 의미를 찾아요. 균형이 잘 맞아요.", "One learns by diving in, the other by finding meaning. A well-balanced pair."),
    funCombo: studyBuddyText("ESFP", "둘 다 일단 저지르고 보는 스타일! 계획은 없지만 재미는 확실해요.", "Both act first, plan later! No plan, but guaranteed fun."),
    meme: {
      ko: "ESTP: 문법책 3장 보다가 “에이 그냥 나가서 써보자”\n(30분 뒤) 실제로 늘어서 돌아옴 💪",
      en: "ESTP: reads 3 pages of grammar, then \"eh, let's just go use it\"\n(30 minutes later) actually comes back better 💪",
    },
    challenge7Days: [
      { day: 1, ko: "학교 밖에서 한국어로 직접 주문하기", en: "Order something in Korean off campus" },
      { day: 2, ko: "길 가는 사람에게 한국어로 길 물어보기", en: "Ask someone for directions in Korean" },
      { day: 3, ko: "어제 배운 표현 오늘 다른 상황에서 써보기", en: "Use yesterday's expression in a different situation today" },
      { day: 4, ko: "짧은 회화 챌린지 영상 따라해보기", en: "Follow along with a short conversation challenge video" },
      { day: 5, ko: "실수했던 표현 다시 정확하게 써보기", en: "Re-try an expression you got wrong, correctly this time" },
      { day: 6, ko: "새로운 장소에 가서 한국어로 도움 요청해보기", en: "Go somewhere new and ask for help in Korean" },
      { day: 7, ko: "이번 주 가장 실전이었던 순간 기록하기", en: "Record your most real-world moment of the week" },
    ],
  },

  ESTJ: {
    code: "ESTJ",
    emoji: "✅",
    titleKo: "한국어 미션 관리자",
    titleEn: "The Korean Mission Manager",
    taglineKo: "사람과 배우고, 경험 중심으로 이해하고, 논리로 분석하고, 계획을 세워 실행하는 학습자",
    taglineEn: "You learn with people, through real experience, with logic, and by executing a clear plan.",
    descriptionKo: "체계적인 계획표와 명확한 기준이 있을 때 안심하고 실력이 늘어요. 스터디 그룹에서도 진도와 규칙을 잘 관리하는 든든한 존재예요.",
    descriptionEn: "You feel secure and improve steadily when there's a systematic plan and clear standards. In a study group, you're the reliable one who manages progress and rules well.",
    strengths: [
      { ko: "정해진 계획을 흔들림 없이 실행해요.", en: "You execute a set plan without wavering." },
      { ko: "스터디 그룹의 진도와 규칙을 잘 관리해요.", en: "You manage a study group's pace and rules well." },
      { ko: "반복 학습을 성실하게 지속해요.", en: "You stick faithfully to repeated practice." },
    ],
    cautions: [
      { ko: "예상 밖의 변수가 생기면 스트레스를 받아요.", en: "Unexpected changes can stress you out." },
      { ko: "정해진 방식 밖의 창의적 표현은 낯설어해요.", en: "Creative expressions outside the standard form can feel unfamiliar." },
    ],
    bestMethods: [
      { ko: "구체적인 학습 계획표 만들고 체크하기", en: "Making and checking off a concrete study plan" },
      { ko: "기출문제·공식 교재로 체계적으로 학습하기", en: "Studying systematically with past papers and official textbooks" },
      { ko: "스터디 그룹의 규칙과 일정 관리 맡기", en: "Taking charge of a study group's rules and schedule" },
    ],
    skills: {
      listening: { ko: "뉴스, 공지사항처럼 명확한 정보 전달 콘텐츠가 잘 맞아요.", en: "Clear, information-driven content like news or announcements suits you well." },
      speaking: { ko: "정해진 주제로 발표 연습을 하면 자신감이 생겨요.", en: "Practicing presentations on a set topic builds your confidence." },
      reading: { ko: "공식 교재나 안내문처럼 구조화된 글이 잘 맞아요.", en: "Structured texts like official textbooks or notices suit you well." },
      writing: { ko: "형식이 명확한 보고서나 요약문 쓰기가 잘 맞아요.", en: "Clearly formatted reports or summaries suit you well." },
    },
    difficultMethod: {
      titleKo: "이렇게 공부하면 쉽게 지칠 수 있어요",
      titleEn: "This approach can drain you fast",
      ko: "정해진 목표나 순서 없이 그날그날 마음대로 공부하기",
      en: "Studying whatever comes to mind, with no set goal or order",
    },
    alternativeMethod: {
      ko: "아주 작은 계획표라도 미리 만들어두면 훨씬 편해질 거예요.",
      en: "Even a small pre-made plan will make things much easier for you.",
    },
    contentRecommendations: [
      { ko: "TOPIK 공식 기출문제 자료", en: "Official TOPIK past exam materials" },
      { ko: "뉴스·공지형 콘텐츠", en: "News and announcement-style content" },
      { ko: "체계적인 커리큘럼의 온라인 강의", en: "Systematically structured online courses" },
    ],
    campusMission: {
      ko: "오늘 이번 주 학습 계획표를 종이나 앱에 구체적으로 적어보세요.",
      en: "Today, write out this week's concrete study plan on paper or in an app.",
    },
    studyBuddy: studyBuddyText("INFP", "한 명은 틀을 잡고, 한 명은 감성을 더해요. 서로에게 좋은 자극이 돼요.", "One builds the structure, the other adds heart. You inspire each other well."),
    funCombo: studyBuddyText("ESFJ", "둘 다 계획형! 스터디 시간표가 분 단위로 완벽하게 짜여요.", "Both planners! Your study schedule ends up planned down to the minute."),
    meme: {
      ko: "시험 D-14\n다른 학생: 😱\nESTJ: 계획표 이미 있음 ✅",
      en: "Exam in 14 days\nOther student: 😱\nESTJ: Already has a plan ✅",
    },
    challenge7Days: [
      { day: 1, ko: "이번 주 학습 계획표 작성하기", en: "Write this week's study plan" },
      { day: 2, ko: "계획표대로 오늘 학습량 완료하기", en: "Complete today's study amount as planned" },
      { day: 3, ko: "기출문제 한 세트 풀어보기", en: "Solve one set of past exam questions" },
      { day: 4, ko: "틀린 문제 원인 정리하기", en: "Organize why you got certain questions wrong" },
      { day: 5, ko: "정해진 주제로 짧은 발표 연습하기", en: "Practice a short presentation on a set topic" },
      { day: 6, ko: "이번 주 계획 달성률 점검하기", en: "Check this week's plan completion rate" },
      { day: 7, ko: "다음 주 계획표 미리 만들기", en: "Prepare next week's plan in advance" },
    ],
  },

  INFP: {
    code: "INFP",
    emoji: "🌙",
    titleKo: "감성 한국어 수집가",
    titleEn: "The Sentimental Korean Collector",
    taglineKo: "혼자 몰입하고, 맥락으로 이해하고, 마음으로 소통하고, 자유롭게 탐색하는 학습자",
    taglineEn: "You learn in solitary focus, through context, from the heart, and always exploring freely.",
    descriptionKo: "마음에 와닿는 표현을 조용히 수집하는 타입이에요. 가사, 대사, 짧은 문장 하나가 오래 기억에 남고, 그 감정을 따라가다 보면 한국어가 자연스럽게 스며들어요.",
    descriptionEn: "You quietly collect expressions that touch your heart. A single lyric, line, or sentence stays with you, and following that feeling lets Korean naturally sink in.",
    strengths: [
      { ko: "마음에 와닿는 표현을 오래 기억해요.", en: "You remember expressions that resonate with you for a long time." },
      { ko: "혼자서도 꾸준히 몰입해서 공부해요.", en: "You immerse yourself in study steadily, even alone." },
      { ko: "글쓰기로 섬세한 감정을 잘 표현해요.", en: "You express subtle emotions well through writing." },
    ],
    cautions: [
      { ko: "실제로 말해보는 걸 망설이는 편이에요.", en: "You tend to hesitate before actually speaking." },
      { ko: "기분이 가라앉으면 공부 동기도 함께 줄어들어요.", en: "Your motivation drops along with your mood." },
    ],
    bestMethods: [
      { ko: "좋아하는 가사나 대사로 표현 수집하기", en: "Collecting expressions from favorite lyrics or lines" },
      { ko: "한국어 일기 쓰며 감정 표현 연습하기", en: "Practicing emotional expression by keeping a Korean diary" },
      { ko: "부담 없는 1:1 대화 상대와 천천히 말해보기", en: "Speaking slowly with a low-pressure one-on-one partner" },
    ],
    skills: {
      listening: { ko: "감성적인 발라드나 잔잔한 라디오가 잘 맞아요.", en: "Emotional ballads or calm radio suit you well." },
      speaking: { ko: "부담 없는 한 사람과 천천히, 짧게 말하는 것부터 시작하세요.", en: "Start by speaking slowly and briefly with just one comfortable person." },
      reading: { ko: "에세이, 시, 짧은 소설처럼 감정이 담긴 글이 잘 맞아요.", en: "Emotionally rich writing — essays, poems, short stories — suits you well." },
      writing: { ko: "일기나 편지처럼 나만의 속도로 쓰는 글쓰기가 잘 맞아요.", en: "Diary entries or letters written at your own pace suit you well." },
    },
    difficultMethod: {
      titleKo: "이렇게 공부하면 쉽게 지칠 수 있어요",
      titleEn: "This approach can drain you fast",
      ko: "낯선 사람들 앞에서 큰 소리로 발표하듯 말하기 연습하기",
      en: "Practicing speaking loudly in front of a room of strangers",
    },
    alternativeMethod: {
      ko: "믿을 수 있는 한 사람과 조용히 대화하며 말하기 연습을 시작해보세요.",
      en: "Start speaking practice with a quiet conversation with one trusted person.",
    },
    contentRecommendations: [
      { ko: "감성 발라드·가사 분석 콘텐츠", en: "Emotional ballads and lyric analysis content" },
      { ko: "한국어 에세이·짧은 소설", en: "Korean essays and short stories" },
      { ko: "차분한 톤의 한국어 라디오·팟캐스트", en: "Calm-toned Korean radio and podcasts" },
    ],
    campusMission: {
      ko: "오늘 마음에 드는 한국어 문장 하나를 골라 다이어리에 적어보세요.",
      en: "Today, pick one Korean sentence you love and write it in your diary.",
    },
    studyBuddy: studyBuddyText("ESTJ", "한 명은 감성을 더하고, 한 명은 틀을 잡아요. 서로에게 좋은 자극이 돼요.", "One adds heart, the other builds structure. You inspire each other well."),
    funCombo: studyBuddyText("INTP", "둘 다 조용히 몰입! 대화는 적지만 텔레파시로 통해요 🤫", "Both quietly absorbed! Barely talk, but somehow understand each other telepathically 🤫"),
    meme: {
      ko: "INFP: 노래 가사 한 줄 듣고 3일째 그 표현만 생각 중... 🎵",
      en: "INFP: heard one line of a song and has been thinking about that phrase for 3 days now 🎵",
    },
    challenge7Days: [
      { day: 1, ko: "마음에 드는 한국어 문장 하나 다이어리에 적기", en: "Write one Korean sentence you love in your diary" },
      { day: 2, ko: "좋아하는 노래 가사에서 표현 하나 찾아보기", en: "Find one expression from a favorite song's lyrics" },
      { day: 3, ko: "오늘의 감정을 한국어 한 문장으로 써보기", en: "Write today's feeling in one Korean sentence" },
      { day: 4, ko: "믿을 수 있는 친구와 짧게 한국어로 대화하기", en: "Have a short Korean chat with a trusted friend" },
      { day: 5, ko: "좋아하는 문장을 소리 내어 읽어보기", en: "Read your favorite sentence out loud" },
      { day: 6, ko: "이번 주 모은 문장들 다시 읽어보기", en: "Re-read the sentences you collected this week" },
      { day: 7, ko: "가장 좋아하는 문장 하나 친구에게 공유하기", en: "Share your favorite sentence with a friend" },
    ],
  },

  INFJ: {
    code: "INFJ",
    emoji: "🌱",
    titleKo: "의미를 찾는 언어 여행자",
    titleEn: "The Meaning-Seeking Language Traveler",
    taglineKo: "혼자 몰입하고, 맥락으로 이해하고, 마음으로 소통하고, 계획을 세워 나아가는 학습자",
    taglineEn: "You learn in solitary focus, through context, from the heart, and with a quiet plan.",
    descriptionKo: "표현 하나를 배워도 “이 말에 담긴 의미가 뭘까”를 곰곰이 생각해요. 조용히, 그러나 꾸준히 자신만의 방향을 가지고 한국어와 한국 문화를 깊이 이해해가요.",
    descriptionEn: "Even with a single expression, you quietly ponder \"what does this really mean?\" You move quietly but steadily, with your own clear direction, understanding Korean language and culture deeply.",
    strengths: [
      { ko: "표현의 맥락과 의미를 깊이 이해해요.", en: "You deeply understand the context and meaning behind expressions." },
      { ko: "조용하지만 꾸준하게 목표를 향해 나아가요.", en: "You move quietly but consistently toward your goals." },
      { ko: "문화적 배경까지 함께 배우는 걸 좋아해요.", en: "You enjoy learning the cultural background along with the language." },
    ],
    cautions: [
      { ko: "완벽하게 이해할 때까지 넘어가지 못할 때가 있어요.", en: "You sometimes can't move on until you fully understand something." },
      { ko: "혼자 고민하다 질문할 타이밍을 놓쳐요.", en: "You mull things over alone and miss the moment to ask a question." },
    ],
    bestMethods: [
      { ko: "표현의 문화적 배경까지 찾아보며 학습하기", en: "Learning by researching the cultural background of expressions" },
      { ko: "나만의 학습 저널 꾸준히 쓰기", en: "Keeping a personal learning journal consistently" },
      { ko: "소규모 깊이 있는 대화 모임 참여하기", en: "Joining small, in-depth conversation groups" },
    ],
    skills: {
      listening: { ko: "다큐멘터리나 인문학 강연처럼 깊이 있는 콘텐츠가 잘 맞아요.", en: "In-depth content like documentaries or humanities lectures suits you well." },
      speaking: { ko: "소수의 신뢰하는 사람과 깊은 주제로 대화하며 연습하세요.", en: "Practice by discussing deep topics with a few trusted people." },
      reading: { ko: "문화, 철학을 다룬 글이나 인터뷰가 잘 맞아요.", en: "Writing on culture and philosophy, or interviews, suits you well." },
      writing: { ko: "생각을 정리하는 성찰적인 글쓰기가 잘 맞아요.", en: "Reflective writing that organizes your thoughts suits you well." },
    },
    difficultMethod: {
      titleKo: "이렇게 공부하면 쉽게 지칠 수 있어요",
      titleEn: "This approach can drain you fast",
      ko: "표면적인 표현만 빠르게 암기하고 다음으로 넘어가기",
      en: "Quickly memorizing surface-level expressions and moving right on",
    },
    alternativeMethod: {
      ko: "완벽하지 않아도 괜찮으니, 이해한 만큼만 표현해보는 연습을 해보세요.",
      en: "It's okay not to be perfect — practice expressing just as much as you understand.",
    },
    contentRecommendations: [
      { ko: "한국 문화 다큐멘터리", en: "Korean culture documentaries" },
      { ko: "인문학·에세이 강연 콘텐츠", en: "Humanities and essay lecture content" },
      { ko: "깊이 있는 인터뷰 콘텐츠", en: "In-depth interview content" },
    ],
    campusMission: {
      ko: "오늘 배운 표현 하나의 문화적 배경을 검색해보세요.",
      en: "Today, look up the cultural background behind one expression you learned.",
    },
    studyBuddy: studyBuddyText("ESTP", "한 명은 의미를 찾고, 한 명은 부딪히며 배워요. 균형이 잘 맞아요.", "One finds meaning, the other learns by diving in. A well-balanced pair."),
    funCombo: studyBuddyText("INTJ", "둘 다 깊이 파고드는 스타일! 대화가 시작되면 두 시간이 훌쩍 가요.", "Both go deep! Once the conversation starts, two hours fly by."),
    meme: {
      ko: "INFJ: 표현 하나 배우고 그 뜻의 유래까지 검색 중...\n(정작 숙제는 아직 시작도 안 함) 🌱",
      en: "INFJ: learns one expression, then researches its entire origin...\n(hasn't started the actual homework yet) 🌱",
    },
    challenge7Days: [
      { day: 1, ko: "표현 하나의 문화적 배경 검색해보기", en: "Look up the cultural background of one expression" },
      { day: 2, ko: "학습 저널에 오늘 느낀 점 적기", en: "Write today's reflections in your learning journal" },
      { day: 3, ko: "신뢰하는 친구와 깊은 주제로 짧게 대화하기", en: "Have a short deep conversation with a trusted friend" },
      { day: 4, ko: "한국 문화 다큐멘터리 10분 시청하기", en: "Watch 10 minutes of a Korean culture documentary" },
      { day: 5, ko: "이해한 만큼만 표현해서 말해보기", en: "Say something out loud, just as much as you understand" },
      { day: 6, ko: "이번 주 배운 것 중 인상 깊었던 것 정리하기", en: "Summarize the most memorable thing you learned this week" },
      { day: 7, ko: "다음 주 탐구하고 싶은 주제 정하기", en: "Choose a topic you want to explore next week" },
    ],
  },

  INTP: {
    code: "INTP",
    emoji: "🔍",
    titleKo: "한국어 원리 탐정",
    titleEn: "The Korean Grammar Detective",
    taglineKo: "혼자 몰입하고, 맥락으로 이해하고, 논리로 분석하고, 자유롭게 탐색하는 학습자",
    taglineEn: "You learn in solitary focus, through context, with logic, and always exploring freely.",
    descriptionKo: "“이 문법은 왜 이렇게 생겼을까”를 파고드는 걸 좋아하는 타입이에요. 혼자 조용히 규칙을 분석하고 원리를 이해하면 그 어떤 응용도 자유자재로 할 수 있어요.",
    descriptionEn: "You love digging into \"why is this grammar structured this way?\" Once you quietly analyze the rules and understand the logic on your own, you can apply it freely to anything.",
    strengths: [
      { ko: "문법의 원리를 정확하게 파악해요.", en: "You grasp the underlying logic of grammar accurately." },
      { ko: "혼자서도 깊이 있게 탐구해요.", en: "You explore deeply, even on your own." },
      { ko: "논리적으로 예외 규칙까지 이해해요.", en: "You logically understand even the exceptions to rules." },
    ],
    cautions: [
      { ko: "이론에 머물러 실제 말하기를 미룰 수 있어요.", en: "You may stay in theory and put off actually speaking." },
      { ko: "완벽히 이해하기 전엔 입을 떼기 부담스러워해요.", en: "You feel uneasy speaking before fully understanding something." },
    ],
    bestMethods: [
      { ko: "문법 원리를 스스로 정리한 나만의 노트 만들기", en: "Making your own notes on grammar logic" },
      { ko: "예외 규칙을 찾아 분류해보기", en: "Finding and categorizing exceptions to rules" },
      { ko: "이해한 원리를 짧게라도 소리 내어 말해보기", en: "Saying the logic you understood out loud, even briefly" },
    ],
    skills: {
      listening: { ko: "언어학, 문법 설명 콘텐츠처럼 논리적인 자료가 잘 맞아요.", en: "Logical content like linguistics or grammar explanations suits you well." },
      speaking: { ko: "짧은 문장이라도 이해한 원리를 소리 내어 연습해보세요.", en: "Practice saying the logic you understood out loud, even in short sentences." },
      reading: { ko: "문법서, 언어 분석 자료를 깊이 파고들며 읽으세요.", en: "Dig deeply into grammar books and language analysis materials." },
      writing: { ko: "규칙을 정리한 표나 도식으로 나만의 자료 만들기가 잘 맞아요.", en: "Making your own charts and diagrams summarizing rules suits you well." },
    },
    difficultMethod: {
      titleKo: "이렇게 공부하면 쉽게 지칠 수 있어요",
      titleEn: "This approach can drain you fast",
      ko: "이유를 모른 채 예문만 무작정 암기하기",
      en: "Blindly memorizing example sentences without understanding why",
    },
    alternativeMethod: {
      ko: "먼저 원리를 이해한 뒤, 그 원리로 직접 예문을 만들어보세요.",
      en: "Understand the logic first, then make your own example sentences from it.",
    },
    contentRecommendations: [
      { ko: "한국어 문법 분석 유튜브 채널", en: "Korean grammar analysis YouTube channels" },
      { ko: "언어학 관련 콘텐츠", en: "Linguistics-related content" },
      { ko: "TOPIK 문법 정리 자료", en: "TOPIK grammar summary materials" },
    ],
    campusMission: {
      ko: "오늘 궁금했던 문법 하나의 원리를 스스로 찾아 정리해보세요.",
      en: "Today, research and summarize the logic behind one grammar point you're curious about.",
    },
    studyBuddy: studyBuddyText("ESFJ", "한 명은 원리를 파고들고, 한 명은 관계를 챙겨요. 서로의 빈틈을 채워줘요.", "One digs into the logic, the other tends the relationship. You fill each other's gaps."),
    funCombo: studyBuddyText("INFP", "둘 다 조용히 몰입! 대화는 적지만 텔레파시로 통해요 🤫", "Both quietly absorbed! Barely talk, but somehow understand each other telepathically 🤫"),
    meme: {
      ko: "INTP: 문법 규칙 하나 이해하려고 3시간째 검색 중...\n(말하기는 아직 한 문장도 안 함) 🔍",
      en: "INTP: 3 hours into researching one grammar rule...\n(hasn't spoken a single sentence yet) 🔍",
    },
    challenge7Days: [
      { day: 1, ko: "궁금한 문법 하나 원리 찾아보기", en: "Research the logic of one grammar point" },
      { day: 2, ko: "찾은 원리로 예문 3개 만들어보기", en: "Make 3 example sentences using what you found" },
      { day: 3, ko: "만든 예문 소리 내어 말해보기", en: "Say your example sentences out loud" },
      { day: 4, ko: "예외 규칙 하나 찾아 정리하기", en: "Find and organize one exception to a rule" },
      { day: 5, ko: "친구에게 오늘 배운 원리 설명해보기", en: "Explain today's logic to a friend" },
      { day: 6, ko: "이번 주 정리한 원리 노트 다시 보기", en: "Review this week's logic notes" },
      { day: 7, ko: "다음 주 탐구할 문법 주제 정하기", en: "Choose next week's grammar topic to explore" },
    ],
  },

  INTJ: {
    code: "INTJ",
    emoji: "🧠",
    titleKo: "한국어 시스템 설계자",
    titleEn: "The Korean System Architect",
    taglineKo: "혼자 몰입하고, 맥락으로 이해하고, 논리로 분석하고, 계획을 세워 나아가는 학습자",
    taglineEn: "You learn in solitary focus, through context, with logic, and with a long-term plan.",
    descriptionKo: "장기적인 그림을 그리고 그 안에서 효율적으로 움직이는 타입이에요. 나만의 학습 시스템을 설계하고, 그 시스템이 검증되면 끝까지 밀고 나가요.",
    descriptionEn: "You draw the long-term picture and move efficiently within it. You design your own learning system, and once it's proven, you push it through to the end.",
    strengths: [
      { ko: "장기적인 학습 전략을 잘 설계해요.", en: "You design long-term learning strategies well." },
      { ko: "혼자서도 흔들림 없이 목표를 향해 가요.", en: "You move steadily toward your goal, even alone." },
      { ko: "비효율을 정확히 짚어내고 개선해요.", en: "You precisely spot inefficiencies and improve them." },
    ],
    cautions: [
      { ko: "계획을 짜는 데 시간을 너무 많이 쓸 수 있어요.", en: "You can spend too much time perfecting the plan itself." },
      { ko: "사람들과 어울리는 학습을 우선순위에서 미룰 수 있어요.", en: "You may deprioritize learning that involves socializing." },
    ],
    bestMethods: [
      { ko: "장기 로드맵을 설계하고 단계별로 실행하기", en: "Designing a long-term roadmap and executing it in stages" },
      { ko: "학습 데이터를 기록하고 스스로 분석하기", en: "Recording and analyzing your own learning data" },
      { ko: "검증된 방법을 꾸준히, 깊이 있게 반복하기", en: "Repeating a proven method deeply and consistently" },
    ],
    skills: {
      listening: { ko: "다큐멘터리, 강의처럼 밀도 있는 콘텐츠가 잘 맞아요.", en: "Dense content like documentaries or lectures suits you well." },
      speaking: { ko: "미리 준비한 주제로 혼자 말해보는 연습부터 시작하세요.", en: "Start by practicing speaking alone on a prepared topic." },
      reading: { ko: "체계적인 교재나 논리적인 글이 잘 맞아요.", en: "Systematic textbooks and logically structured writing suit you well." },
      writing: { ko: "구조가 명확한 분석적인 글쓰기가 잘 맞아요.", en: "Clearly structured, analytical writing suits you well." },
    },
    difficultMethod: {
      titleKo: "이렇게 공부하면 쉽게 지칠 수 있어요",
      titleEn: "This approach can drain you fast",
      ko: "즉흥적인 모임에서 계획 없이 바로 대화에 뛰어들기",
      en: "Diving straight into unplanned conversation at a spontaneous gathering",
    },
    alternativeMethod: {
      ko: "말할 주제를 미리 한두 가지 준비해두면 훨씬 편안해질 거예요.",
      en: "Preparing one or two topics in advance will make it much more comfortable.",
    },
    contentRecommendations: [
      { ko: "체계적인 온라인 강의 커리큘럼", en: "Systematically structured online course curricula" },
      { ko: "다큐멘터리·심층 분석 콘텐츠", en: "Documentaries and in-depth analysis content" },
      { ko: "학습 관리 앱", en: "Study tracking and management apps" },
    ],
    campusMission: {
      ko: "오늘 나만의 한국어 학습 로드맵을 큰 틀에서 그려보세요.",
      en: "Today, sketch out the big picture of your own Korean learning roadmap.",
    },
    studyBuddy: studyBuddyText("ESFP", "한 명은 깊이를 더하고, 한 명은 분위기를 띄워요. 뜻밖에 잘 맞는 조합.", "One brings depth, the other brings energy. A surprisingly great match."),
    funCombo: studyBuddyText("INFJ", "둘 다 깊이 파고드는 스타일! 대화가 시작되면 두 시간이 훌쩍 가요.", "Both go deep! Once the conversation starts, two hours fly by."),
    meme: {
      ko: "INTJ: 6개월 학습 로드맵 이미 엑셀로 완성.\n친구: “내일 뭐 공부해?”\nINTJ: “37번째 항목.” 🧠",
      en: "INTJ: already finished a 6-month roadmap in Excel.\nFriend: \"What are you studying tomorrow?\"\nINTJ: \"Item number 37.\" 🧠",
    },
    challenge7Days: [
      { day: 1, ko: "나만의 학습 로드맵 큰 틀 그리기", en: "Sketch the big picture of your own learning roadmap" },
      { day: 2, ko: "이번 주 실행할 세부 단계 정하기", en: "Set the detailed steps for this week" },
      { day: 3, ko: "오늘 학습 결과를 간단히 기록하기", en: "Briefly record today's study results" },
      { day: 4, ko: "말할 주제 하나 준비해서 혼자 말해보기", en: "Prepare one topic and practice speaking alone" },
      { day: 5, ko: "비효율적이었던 부분 하나 개선하기", en: "Improve one inefficient part of your process" },
      { day: 6, ko: "이번 주 데이터 돌아보며 분석하기", en: "Review and analyze this week's data" },
      { day: 7, ko: "다음 단계 로드맵 업데이트하기", en: "Update your roadmap for the next stage" },
    ],
  },

  ISFP: {
    code: "ISFP",
    emoji: "🎨",
    titleKo: "나만의 한국어 크리에이터",
    titleEn: "The Personal Korean Creator",
    taglineKo: "혼자 몰입하고, 경험 중심으로 이해하고, 마음으로 소통하고, 자유롭게 탐색하는 학습자",
    taglineEn: "You learn in solitary focus, through real experience, from the heart, and always exploring freely.",
    descriptionKo: "느낌과 감각으로 한국어를 흡수하는 타입이에요. 사진, 음악, 그림처럼 나만의 방식으로 표현을 기록하고, 조용히 나만의 속도로 완성해가요.",
    descriptionEn: "You absorb Korean through feeling and sensation. You record expressions in your own way — through photos, music, art — and quietly build mastery at your own pace.",
    strengths: [
      { ko: "감각적으로 표현을 자연스럽게 흡수해요.", en: "You naturally absorb expressions through sensation and feel." },
      { ko: "나만의 방식으로 창의적으로 기록해요.", en: "You creatively record what you learn in your own unique way." },
      { ko: "부담 없이 자기 속도로 꾸준히 해요.", en: "You keep going steadily at your own pace, without pressure." },
    ],
    cautions: [
      { ko: "체계적인 정리를 미루는 편이에요.", en: "You tend to put off systematic organization." },
      { ko: "낯선 사람 앞에서 말하는 걸 부담스러워해요.", en: "Speaking in front of strangers feels like a burden." },
    ],
    bestMethods: [
      { ko: "사진·그림 일기로 표현 기록하기", en: "Recording expressions through photo or drawing diaries" },
      { ko: "좋아하는 음악으로 감각적으로 익히기", en: "Absorbing expressions sensorially through favorite music" },
      { ko: "편안한 소규모 모임에서 천천히 말해보기", en: "Speaking slowly in a comfortable small group" },
    ],
    skills: {
      listening: { ko: "감성적인 플레이리스트나 잔잔한 브이로그가 잘 맞아요.", en: "Emotional playlists or calm vlogs suit you well." },
      speaking: { ko: "편안한 친구와 짧고 여유롭게 대화 연습을 하세요.", en: "Practice speaking briefly and comfortably with a relaxed friend." },
      reading: { ko: "그림이 있는 에세이나 감성적인 짧은 글이 잘 맞아요.", en: "Illustrated essays or short emotional writing suits you well." },
      writing: { ko: "사진에 짧은 문장을 붙이는 캡션 쓰기부터 시작하세요.", en: "Start with writing short captions to go with your photos." },
    },
    difficultMethod: {
      titleKo: "이렇게 공부하면 쉽게 지칠 수 있어요",
      titleEn: "This approach can drain you fast",
      ko: "정해진 시간표대로 딱딱하게 문법만 외우기",
      en: "Rigidly memorizing grammar on a fixed schedule",
    },
    alternativeMethod: {
      ko: "좋아하는 사진이나 음악에 표현을 붙여서 나만의 방식으로 기록해보세요.",
      en: "Attach expressions to photos or music you love and record them your own way.",
    },
    contentRecommendations: [
      { ko: "감성 플레이리스트·음악 콘텐츠", en: "Emotional playlists and music content" },
      { ko: "일러스트가 있는 한국어 에세이", en: "Illustrated Korean essays" },
      { ko: "감각적인 브이로그 채널", en: "Sensory, aesthetic vlog channels" },
    ],
    campusMission: {
      ko: "오늘 캠퍼스에서 마음에 드는 순간을 사진으로 찍고 한국어 캡션을 달아보세요.",
      en: "Today, take a photo of a moment you love on campus and write a Korean caption for it.",
    },
    studyBuddy: studyBuddyText("ENTJ", "한 명은 감성을 더하고, 한 명은 방향을 잡아요. 서로에게 없는 걸 채워줘요.", "One adds heart, the other sets the direction. You fill in what the other lacks."),
    funCombo: studyBuddyText("ISTP", "둘 다 조용히 자기 속도로! 말은 적지만 결과물은 확실해요.", "Both quietly working at their own pace! Few words, but solid results."),
    meme: {
      ko: "ISFP: 오늘 배운 표현으로 사진 캡션 완성.\n좋아요 3개, 근데 뿌듯함은 100 🎨",
      en: "ISFP: finishes a photo caption with today's new expression.\n3 likes, but 100% satisfaction 🎨",
    },
    challenge7Days: [
      { day: 1, ko: "마음에 드는 순간 사진 찍고 한국어 캡션 달기", en: "Photograph a favorite moment and caption it in Korean" },
      { day: 2, ko: "좋아하는 노래에서 표현 하나 찾아 기록하기", en: "Find and record one expression from a favorite song" },
      { day: 3, ko: "그림이나 낙서에 한국어 단어 붙여보기", en: "Attach a Korean word to a drawing or doodle" },
      { day: 4, ko: "편안한 친구와 짧게 한국어로 대화하기", en: "Have a short Korean chat with a comfortable friend" },
      { day: 5, ko: "이번 주 기록한 것들 모아서 보기", en: "Look back over everything you've recorded this week" },
      { day: 6, ko: "가장 마음에 드는 기록 하나 소리 내어 읽기", en: "Read your favorite recorded piece out loud" },
      { day: 7, ko: "나만의 방식으로 한 주를 정리해보기", en: "Wrap up the week in your own personal style" },
    ],
  },

  ISFJ: {
    code: "ISFJ",
    emoji: "🌷",
    titleKo: "꾸준한 한국어 성장러",
    titleEn: "The Steady Korean Grower",
    taglineKo: "혼자 몰입하고, 경험 중심으로 이해하고, 마음으로 소통하고, 계획을 세워 나아가는 학습자",
    taglineEn: "You learn in solitary focus, through real experience, from the heart, and with a steady plan.",
    descriptionKo: "화려하진 않지만 매일 조금씩, 확실하게 늘어가는 타입이에요. 익숙한 루틴 안에서 안정감을 느끼고, 배운 건 꼼꼼하게 내 것으로 만들어요.",
    descriptionEn: "You're not flashy, but you improve steadily, a little every day. You feel secure within a familiar routine, and carefully make everything you learn truly your own.",
    strengths: [
      { ko: "꾸준한 루틴을 성실하게 지켜요.", en: "You faithfully maintain a consistent routine." },
      { ko: "배운 내용을 꼼꼼하게 복습해요.", en: "You review what you've learned meticulously." },
      { ko: "실생활에서 바로 쓸 수 있는 표현을 잘 익혀요.", en: "You learn practical, everyday-usable expressions well." },
    ],
    cautions: [
      { ko: "새로운 방식을 시도하는 걸 부담스러워해요.", en: "Trying new methods can feel like a burden." },
      { ko: "실수할까 봐 말하기를 망설여요.", en: "Fear of mistakes makes you hesitate to speak." },
    ],
    bestMethods: [
      { ko: "매일 같은 시간, 짧게라도 꾸준히 공부하기", en: "Studying briefly but consistently at the same time each day" },
      { ko: "실생활 표현 위주로 차곡차곡 익히기", en: "Steadily building up practical, everyday expressions" },
      { ko: "익숙한 친구와 편안하게 복습하기", en: "Reviewing comfortably with a familiar friend" },
    ],
    skills: {
      listening: { ko: "생활 밀착형 라디오나 잔잔한 팟캐스트가 잘 맞아요.", en: "Practical, everyday-life radio or calm podcasts suit you well." },
      speaking: { ko: "익숙한 사람과 매일 짧게 반복해서 연습해보세요.", en: "Practice briefly every day with someone familiar." },
      reading: { ko: "생활 정보나 실용적인 안내문이 잘 맞아요.", en: "Practical life information and guides suit you well." },
      writing: { ko: "매일 짧게 쓰는 한 줄 일기부터 시작하세요.", en: "Start with a one-line diary entry every day." },
    },
    difficultMethod: {
      titleKo: "이렇게 공부하면 쉽게 지칠 수 있어요",
      titleEn: "This approach can drain you fast",
      ko: "낯선 사람들 앞에서 즉흥적으로 발표하듯 말하기",
      en: "Speaking impromptu in front of a room of strangers",
    },
    alternativeMethod: {
      ko: "먼저 익숙한 친구 앞에서 연습한 뒤, 조금씩 범위를 넓혀보세요.",
      en: "Practice in front of a familiar friend first, then gradually widen the circle.",
    },
    contentRecommendations: [
      { ko: "생활 밀착형 한국어 라디오", en: "Practical, everyday-life Korean radio" },
      { ko: "매일 짧게 듣는 팟캐스트", en: "Short daily podcasts" },
      { ko: "실용 회화 중심 교재", en: "Textbooks focused on practical conversation" },
    ],
    campusMission: {
      ko: "오늘 배운 표현 하나를 익숙한 친구에게 딱 한 번 써보세요.",
      en: "Today, use one new expression exactly once with a familiar friend.",
    },
    studyBuddy: studyBuddyText("ENTP", "한 명은 꾸준히 마무리하고, 한 명은 새 아이디어를 던져요. 완성도 최고 조합.", "One steadily finishes, the other throws out new ideas. Top-tier completion rate."),
    funCombo: studyBuddyText("ISTJ", "둘 다 루틴형! 매일 같은 시간에 조용히 함께 공부해요.", "Both routine-lovers! You quietly study together at the same time every day."),
    meme: {
      ko: "ISFJ: 3개월째 매일 단어 5개씩 착실히 외우는 중.\n친구: “안 힘들어?”\nISFJ: “어? 이게 습관인데?” 🌷",
      en: "ISFJ: faithfully memorizing 5 words a day for 3 months straight.\nFriend: \"Isn't that hard?\"\nISFJ: \"Huh? It's just a habit now.\" 🌷",
    },
    challenge7Days: [
      { day: 1, ko: "오늘 배운 표현 익숙한 친구에게 써보기", en: "Use a new expression with a familiar friend" },
      { day: 2, ko: "매일 같은 시간에 짧게 복습하기", en: "Review briefly at the same time as always" },
      { day: 3, ko: "생활 표현 3개 정리해서 노트에 적기", en: "Write down 3 practical expressions in a notebook" },
      { day: 4, ko: "한 줄 일기 한국어로 써보기", en: "Write a one-line diary entry in Korean" },
      { day: 5, ko: "지난주 배운 표현 다시 복습하기", en: "Review an expression you learned last week" },
      { day: 6, ko: "익숙한 친구와 배운 표현으로 대화해보기", en: "Chat with a familiar friend using what you learned" },
      { day: 7, ko: "이번 주 루틴을 잘 지킨 나를 칭찬하기", en: "Give yourself credit for sticking to your routine this week" },
    ],
  },

  ISTP: {
    code: "ISTP",
    emoji: "🛠️",
    titleKo: "실용 한국어 해결사",
    titleEn: "The Practical Korean Problem-Solver",
    taglineKo: "혼자 몰입하고, 경험 중심으로 이해하고, 논리로 분석하고, 자유롭게 탐색하는 학습자",
    taglineEn: "You learn in solitary focus, through real experience, with logic, and always exploring freely.",
    descriptionKo: "필요한 것만 효율적으로 익히는 타입이에요. 말이 많지 않아도 실제 문제(과제, 상황)를 직접 해결하면서 한국어를 자연스럽게 체득해요.",
    descriptionEn: "You efficiently learn only what you actually need. You're not chatty, but you naturally pick up Korean by directly solving real problems — assignments, situations.",
    strengths: [
      { ko: "필요한 표현만 효율적으로 골라 익혀요.", en: "You efficiently pick out only the expressions you need." },
      { ko: "직접 부딪혀 해결하며 배워요.", en: "You learn by directly tackling and solving problems." },
      { ko: "군더더기 없이 핵심만 정리해요.", en: "You organize the core essentials without excess." },
    ],
    cautions: [
      { ko: "필요성을 못 느끼면 학습을 미뤄요.", en: "You put off studying if you don't feel it's necessary." },
      { ko: "감정을 담은 표현을 익히는 데 소홀할 수 있어요.", en: "You may neglect learning emotionally expressive language." },
    ],
    bestMethods: [
      { ko: "실제 필요한 상황(과제, 아르바이트 등) 중심으로 학습하기", en: "Studying based on situations you actually need (assignments, part-time work)" },
      { ko: "핵심만 담은 나만의 요약 노트 만들기", en: "Making your own summary notes with only the essentials" },
      { ko: "직접 해보면서 문제를 해결하는 방식으로 익히기", en: "Learning by directly solving problems as they come up" },
    ],
    skills: {
      listening: { ko: "튜토리얼이나 하우투 영상처럼 실용적인 콘텐츠가 잘 맞아요.", en: "Practical content like tutorials or how-to videos suits you well." },
      speaking: { ko: "필요한 상황을 정해두고 그 상황만 집중적으로 연습하세요.", en: "Pick a specific needed situation and practice that alone, intensively." },
      reading: { ko: "설명서, 안내문처럼 목적이 분명한 글이 잘 맞아요.", en: "Purpose-driven texts like manuals or instructions suit you well." },
      writing: { ko: "간결하고 핵심만 담은 메모 쓰기가 잘 맞아요.", en: "Short, to-the-point notes suit you well." },
    },
    difficultMethod: {
      titleKo: "이렇게 공부하면 쉽게 지칠 수 있어요",
      titleEn: "This approach can drain you fast",
      ko: "당장 쓸모를 못 느끼는 표현을 목적 없이 계속 암기하기",
      en: "Endlessly memorizing expressions you don't see an immediate use for",
    },
    alternativeMethod: {
      ko: "이번 주 실제로 필요한 상황을 하나 정하고, 거기 필요한 표현만 골라 익혀보세요.",
      en: "Pick one real situation you need this week, and learn only the expressions for it.",
    },
    contentRecommendations: [
      { ko: "실용 한국어 튜토리얼 영상", en: "Practical Korean tutorial videos" },
      { ko: "생활 밀착형 하우투 콘텐츠", en: "Practical, everyday how-to content" },
      { ko: "상황별 회화 핵심 표현집", en: "Situation-based key expression guides" },
    ],
    campusMission: {
      ko: "오늘 실제로 필요한 상황 하나를 정하고 그 표현만 딱 익혀보세요.",
      en: "Today, pick one situation you actually need and learn just the expressions for it.",
    },
    studyBuddy: studyBuddyText("ENFJ", "한 명은 문제를 해결하고, 한 명은 사람을 모아요. 든든한 조합이에요.", "One solves the problems, the other brings people together. A rock-solid team."),
    funCombo: studyBuddyText("ISFP", "둘 다 조용히 자기 속도로! 말은 적지만 결과물은 확실해요.", "Both quietly working at their own pace! Few words, but solid results."),
    meme: {
      ko: "ISTP: 필요한 표현 딱 5개만 배움.\n5개로 학교 생활 다 해결함 🛠️",
      en: "ISTP: learned exactly 5 expressions.\nSolved all of campus life with those 5 🛠️",
    },
    challenge7Days: [
      { day: 1, ko: "이번 주 실제로 필요한 상황 하나 정하기", en: "Pick one real situation you need this week" },
      { day: 2, ko: "그 상황에 필요한 표현 3개만 정리하기", en: "Organize just 3 expressions needed for that situation" },
      { day: 3, ko: "실제 상황에서 표현 써보기", en: "Use the expression in the real situation" },
      { day: 4, ko: "다음으로 필요한 상황 하나 더 찾기", en: "Find one more situation you'll need next" },
      { day: 5, ko: "핵심만 담은 요약 노트 만들기", en: "Make a summary note with just the essentials" },
      { day: 6, ko: "이번 주 익힌 표현들 실전에서 다시 써보기", en: "Re-use this week's expressions in real life" },
      { day: 7, ko: "다음 주 필요한 상황 미리 정하기", en: "Decide next week's needed situation in advance" },
    ],
  },

  ISTJ: {
    code: "ISTJ",
    emoji: "📚",
    titleKo: "계획형 한국어 마스터",
    titleEn: "The Methodical Korean Master",
    taglineKo: "혼자 몰입하고, 경험 중심으로 이해하고, 논리로 분석하고, 계획을 세워 실행하는 학습자",
    taglineEn: "You learn in solitary focus, through real experience, with logic, and by executing a clear plan.",
    descriptionKo: "정해진 계획을 성실하게 지키는 타입이에요. 기초부터 차곡차곡, 순서대로 쌓아 올리는 걸 좋아하고, 한 번 만든 루틴은 끝까지 지켜내요.",
    descriptionEn: "You faithfully stick to a set plan. You love building up step by step from the basics, and once you set a routine, you carry it through to the end.",
    strengths: [
      { ko: "정해진 계획을 흔들림 없이 실행해요.", en: "You execute a set plan without wavering." },
      { ko: "기초를 탄탄하게 다져요.", en: "You build a solid foundation from the basics." },
      { ko: "꾸준한 반복 학습에 강해요.", en: "You excel at consistent, repeated practice." },
    ],
    cautions: [
      { ko: "계획에 없는 즉흥적인 상황을 불편해해요.", en: "Unplanned, spontaneous situations can make you uncomfortable." },
      { ko: "완벽하지 않으면 다음 단계로 넘어가길 주저해요.", en: "You hesitate to move on until things feel perfect." },
    ],
    bestMethods: [
      { ko: "공식 교재로 기초부터 순서대로 학습하기", en: "Studying step by step from the basics with an official textbook" },
      { ko: "매일 정해진 분량 꾸준히 반복하기", en: "Consistently repeating a set daily amount" },
      { ko: "학습 기록을 표로 만들어 관리하기", en: "Managing study records with a tracking chart" },
    ],
    skills: {
      listening: { ko: "정규 강의나 교재 음원처럼 체계적인 콘텐츠가 잘 맞아요.", en: "Systematic content like formal lectures or textbook audio suits you well." },
      speaking: { ko: "미리 준비한 표현부터 순서대로 차근차근 연습하세요.", en: "Practice prepared expressions step by step, in order." },
      reading: { ko: "공식 교재나 정리된 문법서가 잘 맞아요.", en: "Official textbooks or well-organized grammar books suit you well." },
      writing: { ko: "형식이 정해진 짧은 글쓰기부터 차곡차곡 연습하세요.", en: "Build up practice with short, clearly formatted writing." },
    },
    difficultMethod: {
      titleKo: "이렇게 공부하면 쉽게 지칠 수 있어요",
      titleEn: "This approach can drain you fast",
      ko: "정해진 순서 없이 여기저기 흥미가는 대로 공부하기",
      en: "Studying wherever your interest wanders, with no set order",
    },
    alternativeMethod: {
      ko: "느슨해도 괜찮으니, 작은 단위의 순서를 미리 정해두고 시작해보세요.",
      en: "It's okay to keep it loose — just decide a small order in advance before starting.",
    },
    contentRecommendations: [
      { ko: "공식 교재 기반 강의", en: "Lectures based on official textbooks" },
      { ko: "TOPIK 단계별 학습 자료", en: "TOPIK level-by-level study materials" },
      { ko: "학습 기록·관리 앱", en: "Study tracking and management apps" },
    ],
    campusMission: {
      ko: "오늘 이번 주 학습 분량표를 만들고 첫 번째 칸을 채워보세요.",
      en: "Today, make this week's study chart and fill in the first box.",
    },
    studyBuddy: studyBuddyText("ENFP", "한 명은 계획대로 끝까지 가고, 한 명은 새로운 활동을 시작해요. 완벽한 밸런스!", "One finishes what's planned, the other starts new things. A perfect balance!"),
    funCombo: studyBuddyText("ISFJ", "둘 다 루틴형! 매일 같은 시간에 조용히 함께 공부해요.", "Both routine-lovers! You quietly study together at the same time every day."),
    meme: {
      ko: "시험 D-14\n다른 학생: 😱\nISTJ: 계획표 이미 있음 ✅",
      en: "Exam in 14 days\nOther student: 😱\nISTJ: Already has a plan ✅",
    },
    challenge7Days: [
      { day: 1, ko: "이번 주 학습 분량표 만들기", en: "Make this week's study amount chart" },
      { day: 2, ko: "오늘 분량 정확히 채우기", en: "Complete exactly today's planned amount" },
      { day: 3, ko: "기초 문법 하나 다시 복습하기", en: "Review one basic grammar point again" },
      { day: 4, ko: "정해진 순서대로 다음 단원 시작하기", en: "Start the next unit in the planned order" },
      { day: 5, ko: "준비한 표현으로 짧게 말해보기", en: "Say a prepared expression out loud" },
      { day: 6, ko: "이번 주 학습 기록 정리하기", en: "Organize this week's study record" },
      { day: 7, ko: "다음 주 분량표 미리 만들기", en: "Prepare next week's study chart in advance" },
    ],
  },
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { PROFILES, STRONGEST_ADVICE };
}
