/**
 * Korean Learning Type - Question Data
 * 24 core questions (6 per axis: EI, SN, TF, JP) grouped into 3 campus-day chapters,
 * plus 4 tie-breaker questions (one per axis) used when an axis ends in a 3:3 tie.
 *
 * Each question:
 *   id, chapter, axis, context: {emoji, timeKo, placeKo}, promptKo, promptEn,
 *   optionA: { textKo, textEn, value }, optionB: { textKo, textEn, value },
 *   reactionA / reactionB (optional, shown on ~25-30% of questions)
 */

const CHAPTERS = [
  {
    id: 1,
    key: "morning",
    emoji: "☀️",
    titleKo: "굿모닝 캠퍼스",
    titleEn: "GOOD MORNING",
    introKo: "한국 대학에서의 하루가 시작돼요!",
    introEn: "Your day at a Korean university begins!",
    outroKo: "오전 수업 완료! 이제 점심을 먹으러 가볼까요?",
    outroEn: "Morning classes complete! Time for lunch.",
    outroEmoji: "☀️",
  },
  {
    id: 2,
    key: "campus",
    emoji: "🎒",
    titleKo: "캠퍼스 라이프",
    titleEn: "CAMPUS LIFE",
    introKo: "점심시간, 캠퍼스 곳곳에서 새로운 일들이 벌어져요.",
    introEn: "Lunchtime — campus life kicks into gear.",
    outroKo: "수업은 끝났지만 진짜 캠퍼스 라이프는 지금부터!",
    outroEn: "Classes are over, but the real campus life starts now!",
    outroEmoji: "🌆",
  },
  {
    id: 3,
    key: "afterclass",
    emoji: "🌙",
    titleKo: "방과 후",
    titleEn: "AFTER CLASS",
    introKo: "수업이 끝난 후, 진짜 나의 한국어 생활이 시작돼요.",
    introEn: "After class, your real Korean life begins.",
    outroKo: "Campus Day Complete!",
    outroEn: "Campus Day Complete!",
    outroEmoji: "🎉",
  },
];

const QUESTIONS = [
  // ===== Chapter 1: Morning (Q1-8) =====
  {
    id: 1,
    chapter: 1,
    axis: "EI",
    context: { emoji: "🛏️", timeKo: "8:00 · 기숙사", timeEn: "8:00 AM · Dorm" },
    promptKo: "아침에 기숙사에서 눈을 떴어요. 오늘 한국어 공부, 어떻게 시작할까요?",
    promptEn: "You wake up in your dorm. How do you start today's Korean study?",
    optionA: {
      textKo: "룸메이트나 친구를 깨워서 같이 이야기하며 하루를 시작해요.",
      textEn: "I wake up my roommate or friend and start the day chatting.",
      value: "E",
    },
    optionB: {
      textKo: "혼자 조용히 오늘 배울 단어를 정리하며 하루를 시작해요.",
      textEn: "I quietly organize today's vocabulary by myself.",
      value: "I",
    },
    reactionA: "🗣️ 사람과 함께 시작하는 스타일!",
    reactionB: "🧘 혼자 정리하며 시작하는 스타일!",
  },
  {
    id: 2,
    chapter: 1,
    axis: "JP",
    context: { emoji: "🚶", timeKo: "8:40 · 등굣길", timeEn: "8:40 AM · On the way to class" },
    promptKo: "학교 가는 길, 오늘 공부 계획은 어떻게 되어 있나요?",
    promptEn: "On your way to school — what does today's study plan look like?",
    optionA: {
      textKo: "오늘 공부할 시간표를 미리 정해뒀어요. 계획대로 움직여요.",
      textEn: "I already set a study schedule and follow it.",
      value: "J",
    },
    optionB: {
      textKo: "일단 학교에 가서 그때그때 상황에 맞게 정해요.",
      textEn: "I just go and decide as things come up.",
      value: "P",
    },
  },
  {
    id: 3,
    chapter: 1,
    axis: "SN",
    context: { emoji: "📖", timeKo: "9:00 · 한국어 수업", timeEn: "9:00 AM · Korean Class" },
    promptKo: "새 단원 첫 페이지를 펼쳤어요. 어디에 먼저 눈이 가나요?",
    promptEn: "You open the first page of a new unit. What catches your eye first?",
    optionA: {
      textKo: "실제 대화 예문부터 살펴봐요.",
      textEn: "I look at the example dialogues first.",
      value: "S",
    },
    optionB: {
      textKo: "이 단원이 전체적으로 무슨 주제인지 큰 그림부터 봐요.",
      textEn: "I look at the big picture — what's this unit really about.",
      value: "N",
    },
  },
  {
    id: 4,
    chapter: 1,
    axis: "TF",
    context: { emoji: "✨", timeKo: "9:20 · 새로운 표현", timeEn: "9:20 AM · A New Expression" },
    promptKo: "오늘 새로운 표현을 배웠어요. 어떻게 기억하나요?",
    promptEn: "You just learned a new expression. How do you remember it?",
    optionA: {
      textKo: "문법 규칙과 구조를 분석해서 이해해요.",
      textEn: "I analyze the grammar structure to understand it.",
      value: "T",
    },
    optionB: {
      textKo: "그 표현을 쓸 때의 상황이나 느낌을 떠올리며 기억해요.",
      textEn: "I remember it by imagining the feeling or situation.",
      value: "F",
    },
  },
  {
    id: 5,
    chapter: 1,
    axis: "EI",
    context: { emoji: "🙋", timeKo: "9:45 · 수업 중 질문", timeEn: "9:45 AM · A Question in Class" },
    promptKo: "수업 중 이해가 안 되는 부분이 생겼어요.",
    promptEn: "Something in class doesn't make sense.",
    optionA: {
      textKo: "바로 손을 들고 선생님이나 친구에게 물어봐요.",
      textEn: "I raise my hand and ask right away.",
      value: "E",
    },
    optionB: {
      textKo: "일단 표시해두고 나중에 혼자 찾아봐요.",
      textEn: "I mark it and look it up alone later.",
      value: "I",
    },
    reactionA: "👋 바로 물어보는 스타일!",
    reactionB: "🔍 혼자 파고드는 스타일!",
  },
  {
    id: 6,
    chapter: 1,
    axis: "JP",
    context: { emoji: "📝", timeKo: "10:30 · 과제 안내", timeEn: "10:30 AM · Assignment Given" },
    promptKo: "교수님이 이번 주 과제를 내주셨어요.",
    promptEn: "The professor just assigned homework for the week.",
    optionA: {
      textKo: "바로 일정을 짜고 언제 무엇을 할지 정해요.",
      textEn: "I make a schedule right away for when to do what.",
      value: "J",
    },
    optionB: {
      textKo: "마감 전에 여유롭게, 그때그때 기분 따라 진행해요.",
      textEn: "I take it easy and work on it whenever I feel like it.",
      value: "P",
    },
    reactionA: "🎯 계획부터 잡는 편이네요!",
    reactionB: "🌊 흐름을 따라가는 편이네요!",
  },
  {
    id: 7,
    chapter: 1,
    axis: "SN",
    context: { emoji: "💬", timeKo: "10:50 · 옆자리 학생", timeEn: "10:50 AM · The Student Next to You" },
    promptKo: "옆자리 학생이 방금 배운 표현을 실제로 써서 말을 걸어요.",
    promptEn: "The student next to you uses the expression you just learned.",
    optionA: {
      textKo: "배운 표현 그대로 써서 자연스럽게 대답해요.",
      textEn: "I answer using the exact expression we learned.",
      value: "S",
    },
    optionB: {
      textKo: "그 표현을 응용해서 새로운 말을 만들어 봐요.",
      textEn: "I try applying it to make a new sentence.",
      value: "N",
    },
  },
  {
    id: 8,
    chapter: 1,
    axis: "TF",
    context: { emoji: "🕚", timeKo: "11:30 · 오전 복습", timeEn: "11:30 AM · Morning Review" },
    promptKo: "오전 수업이 끝나고 잠깐 복습할 시간이 생겼어요.",
    promptEn: "Morning classes are done, and you have a moment to review.",
    optionA: {
      textKo: "오늘 배운 문법 규칙을 다시 한 번 정리해요.",
      textEn: "I re-organize today's grammar rules.",
      value: "T",
    },
    optionB: {
      textKo: "오늘 수업에서 재미있었던 순간이나 대화를 떠올려요.",
      textEn: "I recall the fun moments or conversations from class.",
      value: "F",
    },
  },

  // ===== Chapter 2: Campus Life (Q9-16) =====
  {
    id: 9,
    chapter: 2,
    axis: "EI",
    context: { emoji: "☕", timeKo: "12:30 · 학생식당", timeEn: "12:30 PM · Student Cafeteria" },
    promptKo: "처음 보는 한국 학생과 같은 테이블에 앉게 됐어요.",
    promptEn: "You're sitting at the same table with a Korean student you haven't met before.",
    optionA: {
      textKo: "먼저 말을 걸어봐요.",
      textEn: "I start a conversation.",
      value: "E",
    },
    optionB: {
      textKo: "분위기를 먼저 보고 편해지면 이야기해요.",
      textEn: "I wait until I feel comfortable.",
      value: "I",
    },
    reactionA: "👋 오, 바로 말을 거는 스타일!",
    reactionB: "🙂 분위기부터 살피는 스타일!",
  },
  {
    id: 10,
    chapter: 2,
    axis: "JP",
    context: { emoji: "🥤", timeKo: "13:00 · 캠퍼스 카페", timeEn: "1:00 PM · Campus Cafe" },
    promptKo: "카페에서 한국어 공부를 하려고 자리를 잡았어요.",
    promptEn: "You sit down at a cafe to study Korean.",
    optionA: {
      textKo: "오늘 외울 단어 목록과 시간을 미리 정해서 앉아요.",
      textEn: "I decide the word list and time limit before starting.",
      value: "J",
    },
    optionB: {
      textKo: "일단 앉아서 그날 끌리는 걸 공부해요.",
      textEn: "I just sit and study whatever catches my interest.",
      value: "P",
    },
  },
  {
    id: 11,
    chapter: 2,
    axis: "SN",
    context: { emoji: "👥", timeKo: "13:30 · 팀 프로젝트", timeEn: "1:30 PM · Team Project" },
    promptKo: "팀 프로젝트에서 한국어로 자료를 정리해야 해요.",
    promptEn: "You need to organize materials in Korean for a team project.",
    optionA: {
      textKo: "예시 자료나 템플릿을 먼저 찾아서 참고해요.",
      textEn: "I look for examples or templates to reference first.",
      value: "S",
    },
    optionB: {
      textKo: "팀원들과 아이디어를 자유롭게 나누며 큰 방향을 잡아요.",
      textEn: "I freely brainstorm with teammates to set the direction.",
      value: "N",
    },
  },
  {
    id: 12,
    chapter: 2,
    axis: "TF",
    context: { emoji: "🎤", timeKo: "14:00 · 발표 준비", timeEn: "2:00 PM · Presentation Prep" },
    promptKo: "한국어 발표를 준비하고 있어요.",
    promptEn: "You're preparing a presentation in Korean.",
    optionA: {
      textKo: "발표 논리와 구조를 탄탄하게 짜는 데 집중해요.",
      textEn: "I focus on making the logic and structure solid.",
      value: "T",
    },
    optionB: {
      textKo: "듣는 사람이 공감할 수 있는 이야기로 풀어내요.",
      textEn: "I frame it as a story the audience can relate to.",
      value: "F",
    },
  },
  {
    id: 13,
    chapter: 2,
    axis: "EI",
    context: { emoji: "✍️", timeKo: "14:40 · 작문 과제", timeEn: "2:40 PM · Writing Assignment" },
    promptKo: "한국어 작문 과제가 잘 안 풀려요.",
    promptEn: "You're stuck on a Korean writing assignment.",
    optionA: {
      textKo: "친구나 튜터에게 바로 물어보며 같이 풀어요.",
      textEn: "I ask a friend or tutor and work it out together.",
      value: "E",
    },
    optionB: {
      textKo: "혼자 사전과 자료를 찾아보며 해결해요.",
      textEn: "I solve it alone using a dictionary and materials.",
      value: "I",
    },
    reactionA: "🤝 같이 풀어가는 스타일!",
    reactionB: "📖 혼자 해결하는 스타일!",
  },
  {
    id: 14,
    chapter: 2,
    axis: "JP",
    context: { emoji: "📚", timeKo: "15:20 · 도서관", timeEn: "3:20 PM · Library" },
    promptKo: "도서관에서 시험 공부를 시작하려고 해요.",
    promptEn: "You're about to start studying for an exam at the library.",
    optionA: {
      textKo: "공부할 범위와 순서를 목록으로 만들어요.",
      textEn: "I make a list of the scope and order first.",
      value: "J",
    },
    optionB: {
      textKo: "일단 눈에 들어오는 부분부터 자유롭게 시작해요.",
      textEn: "I just start with whatever catches my eye.",
      value: "P",
    },
    reactionA: "📚 먼저 정리하는 스타일이군요!",
    reactionB: "🎲 즉흥적으로 시작하는 스타일이군요!",
  },
  {
    id: 15,
    chapter: 2,
    axis: "SN",
    context: { emoji: "📅", timeKo: "16:00 · 시험 준비", timeEn: "4:00 PM · Exam Prep" },
    promptKo: "한국어 시험이 다가와요. 어떤 방식으로 대비하나요?",
    promptEn: "A Korean exam is coming up. How do you prepare?",
    optionA: {
      textKo: "기출문제와 예상 문제를 반복해서 풀어요.",
      textEn: "I repeatedly solve past and practice questions.",
      value: "S",
    },
    optionB: {
      textKo: "전체 흐름과 개념을 이해하는 데 집중해요.",
      textEn: "I focus on understanding the overall flow and concepts.",
      value: "N",
    },
  },
  {
    id: 16,
    chapter: 2,
    axis: "TF",
    context: { emoji: "🤝", timeKo: "16:30 · 스터디 그룹", timeEn: "4:30 PM · Study Group" },
    promptKo: "스터디 친구가 한국어 실수를 자주 해요.",
    promptEn: "Your study friend keeps making mistakes in Korean.",
    optionA: {
      textKo: "정확한 규칙을 짚어주며 고쳐줘요.",
      textEn: "I point out the exact rule and correct it.",
      value: "T",
    },
    optionB: {
      textKo: "부담 갖지 않도록 격려하면서 같이 연습해요.",
      textEn: "I encourage them so they don't feel pressured, and practice together.",
      value: "F",
    },
  },

  // ===== Chapter 3: After Class (Q17-24) =====
  {
    id: 17,
    chapter: 3,
    axis: "EI",
    context: { emoji: "🎭", timeKo: "17:30 · 동아리", timeEn: "5:30 PM · Club Meeting" },
    promptKo: "한국어 동아리에 처음 가입했어요.",
    promptEn: "You just joined a Korean-language club for the first time.",
    optionA: {
      textKo: "바로 사람들과 어울리며 대화에 참여해요.",
      textEn: "I jump right into conversations with people.",
      value: "E",
    },
    optionB: {
      textKo: "처음엔 지켜보다가 익숙해지면 참여해요.",
      textEn: "I observe first, then join once I feel comfortable.",
      value: "I",
    },
  },
  {
    id: 18,
    chapter: 3,
    axis: "JP",
    context: { emoji: "🇰🇷", timeKo: "18:00 · 한국 친구", timeEn: "6:00 PM · Korean Friend" },
    promptKo: "한국 친구와 언어교환 약속을 잡으려고 해요.",
    promptEn: "You're setting up a language exchange with a Korean friend.",
    optionA: {
      textKo: "요일과 시간, 주제까지 미리 정해서 만나요.",
      textEn: "I fix the day, time, and even the topic in advance.",
      value: "J",
    },
    optionB: {
      textKo: "편할 때 연락해서 즉흥적으로 만나요.",
      textEn: "I text whenever it's convenient and meet spontaneously.",
      value: "P",
    },
  },
  {
    id: 19,
    chapter: 3,
    axis: "SN",
    context: { emoji: "🎪", timeKo: "18:40 · 캠퍼스 축제", timeEn: "6:40 PM · Campus Festival" },
    promptKo: "캠퍼스 축제에서 한국어 체험 부스를 발견했어요.",
    promptEn: "You find a Korean-language experience booth at the campus festival.",
    optionA: {
      textKo: "안내문에 적힌 순서대로 체험해요.",
      textEn: "I follow the steps written on the instructions.",
      value: "S",
    },
    optionB: {
      textKo: "부스를 자유롭게 둘러보며 관심 가는 대로 참여해요.",
      textEn: "I wander freely and join whatever interests me.",
      value: "N",
    },
  },
  {
    id: 20,
    chapter: 3,
    axis: "TF",
    context: { emoji: "🌏", timeKo: "19:10 · 국제학생 행사", timeEn: "7:10 PM · International Student Event" },
    promptKo: "국제학생 행사에서 발표할 기회가 생겼어요.",
    promptEn: "You get a chance to speak at an international student event.",
    optionA: {
      textKo: "정확한 정보와 자료를 준비해서 발표해요.",
      textEn: "I prepare accurate information and data.",
      value: "T",
    },
    optionB: {
      textKo: "사람들과 감정을 나눌 수 있는 이야기로 준비해요.",
      textEn: "I prepare a story that connects emotionally with people.",
      value: "F",
    },
  },
  {
    id: 21,
    chapter: 3,
    axis: "EI",
    context: { emoji: "📱", timeKo: "20:00 · SNS", timeEn: "8:00 PM · Social Media" },
    promptKo: "SNS에서 재미있는 한국어 학습 콘텐츠를 봤어요.",
    promptEn: "You find a fun Korean-learning post on social media.",
    optionA: {
      textKo: "댓글을 남기거나 다른 학습자와 소통해요.",
      textEn: "I leave a comment or chat with other learners.",
      value: "E",
    },
    optionB: {
      textKo: "조용히 저장해두고 혼자 찬찬히 봐요.",
      textEn: "I quietly save it and go through it alone.",
      value: "I",
    },
  },
  {
    id: 22,
    chapter: 3,
    axis: "JP",
    context: { emoji: "🎬", timeKo: "20:40 · K-콘텐츠", timeEn: "8:40 PM · K-Content Time" },
    promptKo: "좋아하는 K-드라마나 K-팝으로 공부하려고 해요.",
    promptEn: "You want to study using a K-drama or K-pop song you like.",
    optionA: {
      textKo: "자막과 대본을 정리해서 계획적으로 공부해요.",
      textEn: "I organize subtitles and scripts to study systematically.",
      value: "J",
    },
    optionB: {
      textKo: "그냥 즐기면서 자연스럽게 표현을 흡수해요.",
      textEn: "I just enjoy it and naturally absorb expressions.",
      value: "P",
    },
  },
  {
    id: 23,
    chapter: 3,
    axis: "SN",
    context: { emoji: "🌆", timeKo: "21:30 · 저녁 복습", timeEn: "9:30 PM · Evening Review" },
    promptKo: "하루를 마무리하며 오늘 배운 걸 복습해요.",
    promptEn: "You're wrapping up the day by reviewing what you learned.",
    optionA: {
      textKo: "오늘 실제로 썼던 표현들을 다시 써봐요.",
      textEn: "I re-practice the expressions I actually used today.",
      value: "S",
    },
    optionB: {
      textKo: "오늘 배운 것들이 서로 어떻게 연결되는지 생각해봐요.",
      textEn: "I think about how today's lessons connect to each other.",
      value: "N",
    },
  },
  {
    id: 24,
    chapter: 3,
    axis: "TF",
    context: { emoji: "🌙", timeKo: "22:00 · 내일 계획", timeEn: "10:00 PM · Tomorrow's Plan" },
    promptKo: "잠들기 전, 내일 한국어 공부 계획을 세워요.",
    promptEn: "Before bed, you're planning tomorrow's Korean study.",
    optionA: {
      textKo: "목표량과 방법을 구체적으로 정해요.",
      textEn: "I set a specific goal amount and method.",
      value: "T",
    },
    optionB: {
      textKo: "내일 만날 사람과의 대화를 기대하며 마음을 정해요.",
      textEn: "I look forward to tomorrow's conversations with people.",
      value: "F",
    },
  },
];

// Tie-breaker questions — one per axis, used only when that axis is 3:3.
const TIEBREAKER_QUESTIONS = {
  EI: {
    id: "TB-EI",
    axis: "EI",
    context: { emoji: "🔥", timeKo: "TIE BREAKER", timeEn: "Tie Breaker" },
    promptKo: "방과 후 자유시간이 생겼어요. 한국어 공부, 어떻게 하고 싶나요?",
    promptEn: "You have free time after class. How do you want to study Korean?",
    optionA: { textKo: "친구를 불러서 같이 카페에서 공부해요.", textEn: "I call a friend and study together at a cafe.", value: "E" },
    optionB: { textKo: "혼자 좋아하는 공간에서 조용히 공부해요.", textEn: "I study quietly alone in my favorite spot.", value: "I" },
  },
  SN: {
    id: "TB-SN",
    axis: "SN",
    context: { emoji: "🔥", timeKo: "TIE BREAKER", timeEn: "Tie Breaker" },
    promptKo: "새로운 문법을 처음 만났을 때, 어떻게 접근하나요?",
    promptEn: "When you meet a new grammar point for the first time, how do you approach it?",
    optionA: { textKo: "예문을 여러 개 보고 패턴을 찾아요.", textEn: "I look at several examples and find the pattern.", value: "S" },
    optionB: { textKo: "이 문법이 왜 이렇게 만들어졌는지 원리를 생각해요.", textEn: "I think about the underlying logic of why it works this way.", value: "N" },
  },
  TF: {
    id: "TB-TF",
    axis: "TF",
    context: { emoji: "🔥", timeKo: "TIE BREAKER", timeEn: "Tie Breaker" },
    promptKo: "친구가 한국어 실수로 속상해해요.",
    promptEn: "Your friend feels upset about a Korean mistake they made.",
    optionA: { textKo: "정확히 어디가 틀렸는지 설명해줘요.", textEn: "I explain exactly what went wrong.", value: "T" },
    optionB: { textKo: "먼저 괜찮다고 다독여줘요.", textEn: "I comfort them first and tell them it's okay.", value: "F" },
  },
  JP: {
    id: "TB-JP",
    axis: "JP",
    context: { emoji: "🔥", timeKo: "TIE BREAKER", timeEn: "Tie Breaker" },
    promptKo: "갑자기 하루가 통째로 비었어요.",
    promptEn: "You suddenly have a whole free day.",
    optionA: { textKo: "밀린 공부 계획표부터 확인해요.", textEn: "I check my backlog of study plans first.", value: "J" },
    optionB: { textKo: "그때 기분에 따라 하고 싶은 걸 해요.", textEn: "I do whatever I feel like in the moment.", value: "P" },
  },
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { CHAPTERS, QUESTIONS, TIEBREAKER_QUESTIONS };
}
